$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$startGatePath = Join-Path $root "docs\art\act_i_paintover_start_gate.json"
$scaffoldPath = Join-Path $root "docs\art\act_i_paintover_source_scaffold.json"
$packetPath = Join-Path $root "docs\art\act_i_paintover_packet.json"
$jsonPath = Join-Path $root "docs\art\act_i_paintover_work_order.json"
$mdPath = Join-Path $root "docs\art\act_i_paintover_work_order.md"

foreach ($path in @($startGatePath, $scaffoldPath, $packetPath)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing Act I paintover work order input: $path"
    }
}

$startGate = Get-Content -LiteralPath $startGatePath -Raw | ConvertFrom-Json
$scaffold = Get-Content -LiteralPath $scaffoldPath -Raw | ConvertFrom-Json
$packet = Get-Content -LiteralPath $packetPath -Raw | ConvertFrom-Json

$gateRooms = @($startGate.rooms)
$scaffoldRooms = @($scaffold.rooms)
$packetRooms = @($packet.rooms)
if ($gateRooms.Count -ne 11 -or $scaffoldRooms.Count -ne 11 -or $packetRooms.Count -ne 11) {
    throw "Act I paintover work order expected 11 rooms in each input."
}

$workRooms = @()
foreach ($gateRoom in $gateRooms) {
    if (-not [bool]$gateRoom.ready_for_paintover) {
        continue
    }

    $scaffoldRoom = @($scaffoldRooms | Where-Object { $_.room_id -eq $gateRoom.room_id })[0]
    $packetRoom = @($packetRooms | Where-Object { $_.room_id -eq $gateRoom.room_id })[0]
    if ($null -eq $scaffoldRoom -or $null -eq $packetRoom) {
        throw "Paintover work order missing scaffold or packet room for: $($gateRoom.room_id)"
    }
    if (@($gateRoom.blockers).Count -gt 0) {
        throw "Paintover work order cannot include blocked room: $($gateRoom.room_id)"
    }
    $workRooms += [ordered]@{
        room_id = $gateRoom.room_id
        room_code = $gateRoom.room_code
        title = $gateRoom.title
        review_status = $gateRoom.review_status
        reviewer_decision = $gateRoom.reviewer_decision
        build_commit = $gateRoom.build_commit
        reviewer = $gateRoom.reviewer
        reviewed_at = $gateRoom.reviewed_at
        decision_note = $gateRoom.decision_note
        look_target_reviewed = $gateRoom.look_target_reviewed
        corvin_action_scaffold_reviewed = $gateRoom.corvin_action_scaffold_reviewed
        target_paintover_source = $gateRoom.target_paintover_source
        scaffold = $gateRoom.scaffold
        blockout_reference = $scaffoldRoom.blockout_reference
        overlay = $scaffoldRoom.overlay
        source_blend = $packetRoom.source_blend
        godot_background = $packetRoom.godot_background
        tone = $packetRoom.tone
        walk_band = $packetRoom.camera.walk_band
        palette_rule = $packet.palette.rule
        layer_stack = @($scaffoldRoom.layer_stack)
        risk_tags = @($scaffoldRoom.risk_tags)
        interaction_priorities = @($packetRoom.interaction_priorities)
        critical_hotspots = @($packetRoom.critical_hotspots)
        close_pair_review = @($packetRoom.close_pair_review)
        paintover_rules = @($packetRoom.paintover_rules)
    }
}

$status = if ($workRooms.Count -gt 0) { "ready_rooms_available" } else { "empty_pending_human_review" }
$workOrder = [ordered]@{
    generated_from = @(
        "docs/art/act_i_paintover_start_gate.json",
        "docs/art/act_i_paintover_source_scaffold.json",
        "docs/art/act_i_paintover_packet.json"
    )
    purpose = "Approved-room final paintover work order for Act I."
    status = $status
    ready_room_count = $workRooms.Count
    blocked_room_count = [int]$startGate.blocked_count
    rule_locks = @(
        "Only rooms with ready_for_paintover true and no blockers may appear here.",
        "Do not create placeholder PSDs to satisfy the work order.",
        "Accepted Litany/Registrar duel format remains locked.",
        "Grey Float remains hard-R: steam, silhouette, privacy, and agency only."
    )
    rooms = $workRooms
}

$workOrder | ConvertTo-Json -Depth 16 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$lines = @(
    "# Act I Paintover Work Order",
    "",
    'Generated by `tools/Export-ActIPaintoverWorkOrder.ps1` from the paintover start gate, source scaffold, and paintover packet.',
    "",
    "Purpose: list only rooms approved for final Act I paintover production.",
    "",
    "Status: $status",
    "Ready rooms in work order: $($workRooms.Count)",
    "Blocked rooms still held by start gate: $([int]$startGate.blocked_count)",
    "",
    "Rule locks:",
    "- Only rooms with `ready_for_paintover == true` and no blockers may appear here.",
    "- Do not create placeholder PSDs to satisfy the work order.",
    "- Accepted Litany/Registrar duel format remains locked.",
    "- Grey Float remains hard-R: steam, silhouette, privacy, and agency only.",
    ""
)

if ($workRooms.Count -eq 0) {
    $lines += "No rooms are approved for final paintover yet. Run the human Act I review, import decisions, and re-run the paintover start gate before starting final PSD work."
} else {
    foreach ($room in $workRooms) {
        $lines += "## $($room.room_code) - $($room.title)"
        $lines += ""
        $lines += "- Review status: $($room.review_status)"
        $lines += "- Reviewer decision: $($room.reviewer_decision)"
        $lines += "- Build commit: $($room.build_commit)"
        $lines += "- Reviewer: $($room.reviewer)"
        $lines += "- Reviewed at: $($room.reviewed_at)"
        $lines += "- Decision note: $($room.decision_note)"
        $lines += "- Look target reviewed: $($room.look_target_reviewed)"
        $lines += "- Corvin action scaffold reviewed: $($room.corvin_action_scaffold_reviewed)"
        $lines += "- Target PSD: ``$($room.target_paintover_source)``"
        $lines += "- Scaffold: ``$($room.scaffold)``"
        $lines += "- Blockout reference: ``$($room.blockout_reference)``"
        $lines += "- Overlay: ``$($room.overlay)``"
        $lines += "- Source blend: ``$($room.source_blend)``"
        $lines += "- Godot background target: ``$($room.godot_background)``"
        $lines += "- Tone: $($room.tone)"
        $lines += "- Walk band: $($room.walk_band)"
        $lines += "- Risk tags: $((@($room.risk_tags) -join ', '))"
        $lines += ""
        $lines += "Layer stack:"
        foreach ($layer in @($room.layer_stack)) {
            $lines += "- $layer"
        }
        $lines += ""
        $lines += "Critical hotspots:"
        foreach ($hotspot in @($room.critical_hotspots)) {
            $roles = @($hotspot.roles) -join ", "
            $lines += "- $($hotspot.label) at $($hotspot.position): $roles. $($hotspot.paintover_note)"
        }
        if (@($room.close_pair_review).Count -gt 0) {
            $lines += ""
            $lines += "Close-pair review:"
            foreach ($pair in @($room.close_pair_review)) {
                $lines += "- $pair"
            }
        }
        $lines += ""
        $lines += "Paintover rules:"
        foreach ($rule in @($room.paintover_rules)) {
            $lines += "- $rule"
        }
        $lines += ""
    }
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I paintover work order JSON -> $jsonPath"
Write-Host "Exported Act I paintover work order report -> $mdPath"
Write-Host "Act I paintover work order: status=$status, ready=$($workRooms.Count), blocked=$([int]$startGate.blocked_count)"
