$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$batchManifestPath = Join-Path $root "docs\vo\vo_recording_batches.json"
$csvPath = Join-Path $root "docs\vo\vo_minor_speaker_decisions_template.csv"
$mdPath = Join-Path $root "docs\vo\vo_minor_speaker_decisions_template.md"

if (-not (Test-Path -LiteralPath $batchManifestPath)) {
    throw "Missing VO recording batch manifest: $batchManifestPath"
}

$manifest = Get-Content -LiteralPath $batchManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$batches = @($manifest.batches | ForEach-Object { $_ })
$uncastBatches = @($batches | Where-Object { $_.cast_status -eq "needs_cast_decision" })

if ($uncastBatches.Count -eq 0) {
    throw "No uncast VO batches found; minor speaker decision template would be empty."
}

$rows = @(
    $uncastBatches |
        Group-Object speaker |
        Sort-Object Name |
        ForEach-Object {
            $speaker = $_.Name
            $speakerBatches = @($_.Group)
            [pscustomobject][ordered]@{
                speaker = $speaker
                decision = "pending"
                cast_as = ""
                scratch_voice = ""
                scratch_voice_id = ""
                consolidate_into = ""
                notes = ""
                batch_count = $speakerBatches.Count
                line_count = ($speakerBatches | Measure-Object -Property line_count -Sum).Sum
                word_count = ($speakerBatches | Measure-Object -Property word_count -Sum).Sum
                locations = (@($speakerBatches | Select-Object -ExpandProperty location -Unique) -join ";")
                knots = (@($speakerBatches | Select-Object -ExpandProperty knot -Unique) -join ";")
                batch_ids = (@($speakerBatches | Select-Object -ExpandProperty batch_id) -join ";")
            }
        }
)

$rows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

$lines = @(
    "# VO Minor Speaker Decision Template",
    "",
    'Generated by `tools/Export-VoMinorSpeakerDecisionTemplate.ps1` from `docs/vo/vo_recording_batches.json`.',
    "",
    "Purpose: make minor-speaker casting and consolidation decisions explicit before scratch VO generation.",
    "",
    "Rows: $($rows.Count)",
    "Uncast batches represented: $($uncastBatches.Count)",
    "",
    "Allowed decisions:",
    "- pending",
    "- cast",
    "- consolidate",
    "- cut_or_rewrite",
    "",
    "Rules:",
    "- `cast` requires `cast_as`, `scratch_voice`, and `scratch_voice_id`.",
    "- `consolidate` requires `consolidate_into` naming an already cast or explicitly cast speaker.",
    "- Every non-pending decision requires notes explaining the casting, consolidation, or script-change rationale.",
    "- Do not assign narrator/audiobook voices to minor character parts by default.",
    "- Do not start scratch generation for batches whose speaker remains pending.",
    "",
    "| Speaker | Batches | Lines | Words | Locations | Knots |",
    "|---|---:|---:|---:|---|---|"
)

foreach ($row in $rows) {
    $lines += "| $($row.speaker) | $($row.batch_count) | $($row.line_count) | $($row.word_count) | $($row.locations) | $($row.knots) |"
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported VO minor speaker decision CSV template -> $csvPath"
Write-Host "Exported VO minor speaker decision brief -> $mdPath"
Write-Host "VO minor speaker decisions: speakers=$($rows.Count), uncastBatches=$($uncastBatches.Count)"
