$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$trackerPath = Join-Path $root "docs\playtest\act_i_review_fix_tracker.json"
$scaffoldPath = Join-Path $root "docs\art\act_i_paintover_source_scaffold.json"
$assetStatusPath = Join-Path $root "docs\art\act_i_background_asset_status.csv"
$jsonPath = Join-Path $root "docs\art\act_i_paintover_start_gate.json"
$mdPath = Join-Path $root "docs\art\act_i_paintover_start_gate.md"

foreach ($path in @($trackerPath, $scaffoldPath, $assetStatusPath)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing Act I paintover start gate input: $path"
    }
}

$tracker = Get-Content -LiteralPath $trackerPath -Raw | ConvertFrom-Json
$scaffold = Get-Content -LiteralPath $scaffoldPath -Raw | ConvertFrom-Json
$assetRows = @(Import-Csv -LiteralPath $assetStatusPath)

$trackerRooms = @($tracker.rooms)
$scaffoldRooms = @($scaffold.rooms)
if ($trackerRooms.Count -ne 11 -or $scaffoldRooms.Count -ne 11) {
    throw "Act I paintover start gate expected 11 tracker/scaffold rooms."
}

$gateRooms = @()
foreach ($room in $trackerRooms) {
    $scaffoldRoom = @($scaffoldRooms | Where-Object { $_.room_id -eq $room.room_id })[0]
    if ($null -eq $scaffoldRoom) {
        throw "Paintover start gate missing scaffold room: $($room.room_id)"
    }
    $paintoverStatus = @($assetRows | Where-Object { $_.room_id -eq $room.room_id -and $_.asset_kind -eq "paintover_source" })[0]
    if ($null -eq $paintoverStatus) {
        throw "Paintover start gate missing paintover status row: $($room.room_id)"
    }

    $blockers = @()
    if ($room.review_status -eq "pending_review" -or $room.reviewer_decision -eq "pending_review") {
        $blockers += "human_review_pending"
    }
    if ($room.review_status -eq "stop_and_redesign" -or $room.reviewer_decision -eq "stop_and_redesign") {
        $blockers += "stop_and_redesign"
    }
    if ($room.review_status -eq "revise_before_art" -or $room.reviewer_decision -eq "revise_before_art") {
        $blockers += "fixes_required_before_art"
    }
    if (-not [bool]$room.approved_for_paintover) {
        $blockers += "not_approved_for_paintover"
    }
    if ($room.review_status -ne "pending_review" -or $room.reviewer_decision -ne "pending_review") {
        if ([string]::IsNullOrWhiteSpace([string]$room.reviewer) -or [string]::IsNullOrWhiteSpace([string]$room.reviewed_at) -or [string]::IsNullOrWhiteSpace([string]$room.decision_note)) {
            $blockers += "review_metadata_missing"
        }
    }
    if ($scaffoldRoom.target_status_remains -ne "pending") {
        $blockers += "scaffold_does_not_preserve_pending_status"
    }

    $ready = $blockers.Count -eq 0
    $gateRooms += [ordered]@{
        room_id = $room.room_id
        room_code = $room.room_code
        title = $room.title
        ready_for_paintover = $ready
        review_status = $room.review_status
        reviewer_decision = $room.reviewer_decision
        reviewer = $room.reviewer
        reviewed_at = $room.reviewed_at
        build_commit = $room.build_commit
        decision_note = $room.decision_note
        approved_for_paintover = [bool]$room.approved_for_paintover
        target_paintover_source = $room.paintover_source
        target_paintover_status = $paintoverStatus.status
        scaffold = $scaffoldRoom.scaffold
        blockers = $blockers
    }
}

$readyRooms = @($gateRooms | Where-Object { $_.ready_for_paintover })
$blockedRooms = @($gateRooms | Where-Object { -not $_.ready_for_paintover })
$gateStatus = if ($blockedRooms.Count -eq 0) { "ready" } else { "blocked_pending_human_review" }

$gate = [ordered]@{
    generated_from = @(
        "docs/playtest/act_i_review_fix_tracker.json",
        "docs/art/act_i_paintover_source_scaffold.json",
        "docs/art/act_i_background_asset_status.csv"
    )
    purpose = "Report whether final Act I paintover production may start per room."
    status = $gateStatus
    ready_count = $readyRooms.Count
    blocked_count = $blockedRooms.Count
    rooms = $gateRooms
}

$gate | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$lines = @(
    "# Act I Paintover Start Gate",
    "",
    'Generated by `tools/Export-ActIPaintoverStartGate.ps1` from the review fix tracker, source scaffold, and background asset status.',
    "",
    "Purpose: report whether final Act I paintover production may start per room.",
    "",
    "Status: $gateStatus",
    "Ready rooms: $($readyRooms.Count)",
    "Blocked rooms: $($blockedRooms.Count)",
    "",
    "This report is expected to remain blocked until human Act I art/readability review signs off room layouts.",
    "",
    "| Room | Ready | Review | Build | Reviewer | Reviewed At | Approved | Target PSD Status | Blockers |",
    "|---|---|---|---|---|---|---|---|---|"
)
foreach ($room in $gateRooms) {
    $blockerText = if (@($room.blockers).Count -eq 0) { "none" } else { @($room.blockers) -join ", " }
    $buildText = if ([string]::IsNullOrWhiteSpace([string]$room.build_commit)) { "none" } else { [string]$room.build_commit }
    $reviewerText = if ([string]::IsNullOrWhiteSpace([string]$room.reviewer)) { "none" } else { [string]$room.reviewer }
    $reviewedAtText = if ([string]::IsNullOrWhiteSpace([string]$room.reviewed_at)) { "none" } else { [string]$room.reviewed_at }
    $lines += "| $($room.room_code) $($room.title) | $($room.ready_for_paintover) | $($room.review_status) | $buildText | $reviewerText | $reviewedAtText | $($room.approved_for_paintover) | $($room.target_paintover_status) | $blockerText |"
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I paintover start gate JSON -> $jsonPath"
Write-Host "Exported Act I paintover start gate report -> $mdPath"
Write-Host "Act I paintover start gate: status=$gateStatus, ready=$($readyRooms.Count), blocked=$($blockedRooms.Count)"
