$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$promptsPath = Join-Path $root "docs\art\act_i_background_source_prompts.json"
$intakePath = Join-Path $root "docs\art\act_i_background_source_intake.json"
$jsonPath = Join-Path $root "docs\art\act_i_background_meshy_queue.json"
$csvPath = Join-Path $root "docs\art\act_i_background_meshy_queue.csv"
$mdPath = Join-Path $root "docs\art\act_i_background_meshy_queue.md"

if (-not (Test-Path -LiteralPath $promptsPath)) {
    throw "Missing Act I background source prompts: $promptsPath"
}
if (-not (Test-Path -LiteralPath $intakePath)) {
    throw "Missing Act I background source intake: $intakePath"
}

$prompts = Get-Content -LiteralPath $promptsPath -Raw | ConvertFrom-Json
$intake = Get-Content -LiteralPath $intakePath -Raw | ConvertFrom-Json
$intakeById = @{}
foreach ($row in @($intake.rows)) {
    $intakeById[[string]$row.id] = $row
}

$meshyPrompts = @($prompts.prompts | Where-Object {
    [string]$_.kind -eq "meshy_source_model" -and [string]$_.tool -eq "Meshy"
} | Sort-Object room_code, name)

$ready = -not [string]::IsNullOrWhiteSpace($env:MESHY_API_KEY)
$apiStatus = if ($ready) { "ready_for_meshing" } else { "blocked_no_meshy_key" }

$queue = @()
foreach ($prompt in $meshyPrompts) {
    if (-not $intakeById.ContainsKey([string]$prompt.id)) {
        throw "Meshy queue item is missing from source intake: $($prompt.id)"
    }
    $intakeRow = $intakeById[[string]$prompt.id]
    $queue += [ordered]@{
        id = $prompt.id
        room_code = $prompt.room_code
        room_id = $prompt.room_id
        room_title = $prompt.room_title
        name = $prompt.name
        source_path = $prompt.source_path
        content_status = $intakeRow.content_status
        generation_status = if ([string]$intakeRow.content_status -eq "present") { "already_downloaded" } else { $apiStatus }
        workflow = "Meshy text-to-3d preview, optional refine only after review, download GLB"
        estimated_preview_credits = 20
        estimated_refine_credits = 10
        prompt = $prompt.prompt
        negative_prompt = $prompt.negative_prompt
        output_contract = $prompt.output_contract
    }
}

$roomCounts = [ordered]@{}
foreach ($group in @($queue | Group-Object { $_["room_code"] } | Sort-Object Name)) {
    $roomCounts[$group.Name] = $group.Count
}

$pendingCount = @($queue | Where-Object { $_["content_status"] -ne "present" }).Count
$presentCount = @($queue | Where-Object { $_["content_status"] -eq "present" }).Count

$payload = [ordered]@{
    generated_from = @(
        "docs/art/act_i_background_source_prompts.json",
        "docs/art/act_i_background_source_intake.json"
    )
    purpose = "Executable queue for Act I Meshy helper GLB source models."
    status = $apiStatus
    guardrails = @(
        "Meshy outputs are helper geometry only.",
        "Download GLB files exactly to the listed source paths.",
        "Do not import Meshy GLBs directly into Godot.",
        "Do not generate final background plates from this queue.",
        "Run source intake after every downloaded GLB.",
        "Preview generation spends Meshy credits and requires explicit user approval before API calls."
    )
    model_count = $queue.Count
    present_count = $presentCount
    pending_count = $pendingCount
    estimated_preview_credits_remaining = $pendingCount * 20
    estimated_refine_credits_if_all_approved = $pendingCount * 10
    room_counts = $roomCounts
    items = $queue
}

$payload | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$csvRows = @()
foreach ($item in $queue) {
    $csvRows += [pscustomobject]@{
        id = $item.id
        room_code = $item.room_code
        room_id = $item.room_id
        name = $item.name
        source_path = $item.source_path
        content_status = $item.content_status
        generation_status = $item.generation_status
        estimated_preview_credits = $item.estimated_preview_credits
        estimated_refine_credits = $item.estimated_refine_credits
        prompt = $item.prompt
        negative_prompt = $item.negative_prompt
        output_contract = $item.output_contract
    }
}
$csvRows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

$fence = ([string][char]96) * 3
$fenceText = "$($fence)text"
$lines = @(
    "# Act I Background Meshy Queue",
    "",
    'Generated by `tools/Export-ActIBackgroundMeshyQueue.ps1` from source prompts and source intake.',
    "",
    "Status: $apiStatus",
    "",
    "Guardrails:",
    "- Meshy outputs are helper geometry only.",
    "- Download GLB files exactly to the listed source paths.",
    "- Do not import Meshy GLBs directly into Godot.",
    "- Do not generate final background plates from this queue.",
    "- Run source intake after every downloaded GLB.",
    "- Preview generation spends Meshy credits and requires explicit user approval before API calls.",
    "",
    "Counts:",
    "- Meshy helper models: $($payload.model_count)",
    "- Present GLBs: $presentCount",
    "- Pending GLBs: $pendingCount",
    "- Estimated preview credits remaining: $($payload.estimated_preview_credits_remaining)",
    "- Estimated refine credits if all approved: $($payload.estimated_refine_credits_if_all_approved)",
    ""
)

if (-not $ready) {
    $lines += "Blocked:"
    $lines += "- `MESHY_API_KEY` was not found in the current environment. Do not create placeholder GLBs."
    $lines += ""
}

foreach ($roomGroup in @($queue | Group-Object { $_["room_code"] } | Sort-Object Name)) {
    $first = @($roomGroup.Group)[0]
    $lines += "## $($first.room_code) - $($first.room_title)"
    $lines += ""
    foreach ($item in @($roomGroup.Group | Sort-Object { $_["name"] })) {
        $lines += "### $($item.id)"
        $lines += ""
        $lines += "- Source: ``$($item.source_path)``"
        $lines += "- Content status: $($item.content_status)"
        $lines += "- Generation status: $($item.generation_status)"
        $lines += "- Estimated preview credits: $($item.estimated_preview_credits)"
        $lines += "- Estimated refine credits: $($item.estimated_refine_credits)"
        $lines += ""
        $lines += "Prompt:"
        $lines += ""
        $lines += $fenceText
        $lines += $item.prompt
        $lines += $fence
        $lines += ""
        $lines += "Negative prompt:"
        $lines += ""
        $lines += $fenceText
        $lines += $item.negative_prompt
        $lines += $fence
        $lines += ""
    }
}

Set-Content -LiteralPath $mdPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8 -NoNewline

Write-Host "Exported Act I Meshy queue JSON -> $jsonPath"
Write-Host "Exported Act I Meshy queue CSV -> $csvPath"
Write-Host "Exported Act I Meshy queue report -> $mdPath"
