$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$packetPath = Join-Path $root "docs\art\act_i_paintover_packet.json"
$scaffoldDir = Join-Path $root "art\src\backgrounds\act_i\paintover_scaffolds"
$jsonPath = Join-Path $root "docs\art\act_i_paintover_source_scaffold.json"
$mdPath = Join-Path $root "docs\art\act_i_paintover_source_scaffold.md"

if (-not (Test-Path -LiteralPath $packetPath)) {
    throw "Missing Act I paintover packet JSON: $packetPath"
}
if (-not (Test-Path -LiteralPath $scaffoldDir)) {
    New-Item -ItemType Directory -Path $scaffoldDir | Out-Null
}

$packet = Get-Content -LiteralPath $packetPath -Raw | ConvertFrom-Json
$rooms = @($packet.rooms)
if ($rooms.Count -ne 11) {
    throw "Act I paintover source scaffold expected 11 rooms, got $($rooms.Count)."
}

$layerStack = @(
    "00_blockout_reference_locked",
    "01_palette_keys_locked",
    "02_value_silhouette_pass",
    "03_navigation_and_walk_band",
    "04_puzzle_hotspot_readability",
    "05_local_lighting_amber_green",
    "06_ink_hatching_texture",
    "07_final_paint",
    "08_export_notes"
)

$roomScaffolds = @()
foreach ($room in $rooms) {
    $scaffoldRelativePath = "art/src/backgrounds/act_i/paintover_scaffolds/$($room.room_id).paintover.md"
    $scaffoldPath = Join-Path $root ($scaffoldRelativePath -replace "/", "\")
    $riskTags = @()
    $priorities = @($room.interaction_priorities)
    if ("wet_verb" -in $priorities) { $riskTags += "wet_readability" }
    if ("confession_source" -in $priorities) { $riskTags += "confession_source_readability" }
    if ("duel" -in $priorities) { $riskTags += "duel_format_lock" }
    if ($room.room_id -eq "grey_float") { $riskTags += "hard_r_float_staging"; $riskTags += "unsafe_amber_exception" }
    if (@($room.close_pair_review).Count -gt 0) { $riskTags += "close_pair_spacing" }
    if ($riskTags.Count -eq 0) { $riskTags += "general_layout_readability" }

    $scaffoldLines = @(
        "# $($room.room_code) - $($room.title) Paintover Source Scaffold",
        "",
        "This is a scaffold for the pending paintover source, not final art.",
        "",
        "- Target PSD: ``$($room.paintover_source)``",
        "- Blockout reference: ``$($room.blockout_export)``",
        "- Godot import target: ``$($room.godot_background)``",
        "- Hotspot overlay: ``$($room.review_overlay)``",
        "- Camera: 1920x1080 fixed side-on, walk band y 650-800",
        "- Tone: $($room.tone)",
        "- Risk tags: $($riskTags -join ', ')",
        "",
        "Layer stack:",
        ""
    )
    foreach ($layer in $layerStack) {
        $scaffoldLines += "- $layer"
    }
    $scaffoldLines += ""
    $scaffoldLines += "Critical hotspots:"
    if (@($room.critical_hotspots).Count -eq 0) {
        $scaffoldLines += "- None beyond navigation and room texture."
    } else {
        foreach ($hotspot in @($room.critical_hotspots)) {
            $scaffoldLines += "- $($hotspot.label) at $($hotspot.position): $((@($hotspot.roles) -join ', '))"
        }
    }
    $scaffoldLines += ""
    $scaffoldLines += "Close-pair review:"
    if (@($room.close_pair_review).Count -eq 0) {
        $scaffoldLines += "- None under threshold."
    } else {
        foreach ($pair in @($room.close_pair_review)) {
            $scaffoldLines += "- $pair"
        }
    }
    $scaffoldLines += ""
    $scaffoldLines += "Paintover lock notes:"
    $scaffoldLines += "- Do not move hotspot centers without updating Godot scenes and regenerating the hotspot map."
    $scaffoldLines += "- Do not create or mark the target PSD complete until final paint exists."
    $scaffoldLines += "- Exported PNG must pass G9/G10 palette audit before it can ship."
    $scaffoldLines += "- Registrar duel scenes must preserve the accepted Litany UI format."
    $scaffoldLines += "- Grey Float must stay hard-R through steam, silhouette, privacy, and labor staging only."

    Set-Content -LiteralPath $scaffoldPath -Value $scaffoldLines -Encoding UTF8

    $roomScaffolds += [ordered]@{
        room_id = $room.room_id
        room_code = $room.room_code
        title = $room.title
        scaffold = $scaffoldRelativePath
        target_paintover_source = $room.paintover_source
        target_status_remains = $room.paintover_status
        blockout_reference = $room.blockout_export
        overlay = $room.review_overlay
        layer_stack = $layerStack
        risk_tags = $riskTags
    }
}

$scaffold = [ordered]@{
    generated_from = "docs/art/act_i_paintover_packet.json"
    purpose = "Create safe per-room paintover source scaffolds without marking final PSD paintover sources present."
    rooms = $roomScaffolds
}

$scaffold | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$lines = @(
    "# Act I Paintover Source Scaffold",
    "",
    'Generated by `tools/Export-ActIPaintoverSourceScaffold.ps1` from `docs/art/act_i_paintover_packet.json`.',
    "",
    "Purpose: provide per-room source scaffolds for final paintover work while keeping official PSD paintover sources pending until real final art exists.",
    "",
    "These scaffolds are not final art and must not be counted as paintover completion.",
    "",
    "| Room | Scaffold | Target PSD | Status Remains | Risk Tags |",
    "|---|---|---|---|---|"
)
foreach ($room in $roomScaffolds) {
    $lines += "| $($room.room_code) $($room.title) | ``$($room.scaffold)`` | ``$($room.target_paintover_source)`` | $($room.target_status_remains) | $((@($room.risk_tags) -join ', ')) |"
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I paintover source scaffold JSON -> $jsonPath"
Write-Host "Exported Act I paintover source scaffold report -> $mdPath"
