$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$promptsPath = Join-Path $root "docs\art\act_i_background_source_prompts.json"
$jsonPath = Join-Path $root "docs\art\act_i_background_source_intake.json"
$csvPath = Join-Path $root "docs\art\act_i_background_source_intake.csv"
$mdPath = Join-Path $root "docs\art\act_i_background_source_intake.md"

if (-not (Test-Path -LiteralPath $promptsPath)) {
    throw "Missing Act I background source prompts: $promptsPath"
}

$promptPayload = Get-Content -LiteralPath $promptsPath -Raw | ConvertFrom-Json
$prompts = @($promptPayload.prompts)

function Get-ExpectedKind {
    param([Parameter(Mandatory=$true)][string]$Kind)

    switch ($Kind) {
        "meshy_source_model" { return "glb" }
        "generated_reference" { return "png" }
        "interactive_layer" { return "psd" }
        "navigation_silhouette" { return "psd" }
        default { throw "Unknown prompt kind for intake: $Kind" }
    }
}

function Test-RelativePathExists {
    param([Parameter(Mandatory=$true)][string]$RelativePath)

    $full = Join-Path $root $RelativePath
    if (Test-Path -LiteralPath $full -PathType Leaf) {
        return (Get-Item -LiteralPath $full)
    }
    return $null
}

$rows = @()
foreach ($prompt in $prompts) {
    $expectedKind = Get-ExpectedKind $prompt.kind
    $sourceItem = Test-RelativePathExists $prompt.source_path
    $runtimeItem = $null
    if (-not [string]::IsNullOrWhiteSpace([string]$prompt.runtime_path)) {
        $runtimeItem = Test-RelativePathExists $prompt.runtime_path
    }

    $status = if ($null -eq $sourceItem) { "pending_source" } else { "source_present_unreviewed" }
    $contentStatus = if ($null -eq $sourceItem) { "missing" } elseif ($sourceItem.Length -le 0) { "zero_byte" } else { "present" }

    $rows += [ordered]@{
        id = $prompt.id
        room_code = $prompt.room_code
        room_id = $prompt.room_id
        room_title = $prompt.room_title
        kind = $prompt.kind
        tool = $prompt.tool
        name = $prompt.name
        status = $status
        content_status = $contentStatus
        expected_file_kind = $expectedKind
        source_path = $prompt.source_path
        source_exists = ($null -ne $sourceItem)
        source_size_bytes = if ($null -eq $sourceItem) { 0 } else { $sourceItem.Length }
        runtime_path = $prompt.runtime_path
        runtime_exists = ($null -ne $runtimeItem)
        runtime_size_bytes = if ($null -eq $runtimeItem) { 0 } else { $runtimeItem.Length }
    }
}

$statusCounts = [ordered]@{}
foreach ($group in @($rows | Group-Object { $_["status"] } | Sort-Object Name)) {
    $statusCounts[$group.Name] = $group.Count
}

$kindCounts = [ordered]@{}
foreach ($group in @($rows | Group-Object { $_["kind"] } | Sort-Object Name)) {
    $kindCounts[$group.Name] = $group.Count
}

$presentCount = @($rows | Where-Object { $_["source_exists"] }).Count
$pendingCount = @($rows | Where-Object { -not $_["source_exists"] }).Count
$zeroByteCount = @($rows | Where-Object { $_["content_status"] -eq "zero_byte" }).Count

$payload = [ordered]@{
    generated_from = "docs/art/act_i_background_source_prompts.json"
    purpose = "Intake/status report for generated Act I background source prompt outputs."
    status = if ($presentCount -eq 0) { "no_source_outputs_present" } else { "source_outputs_present_unreviewed" }
    guardrails = @(
        "Source prompt outputs do not count as final background art.",
        "Meshy GLBs are helper geometry until imported through Blender and paintover.",
        "Generated references are paintover references only and must not be imported as room plates.",
        "Interactive source PSDs require later runtime export and Godot alignment review.",
        "Zero-byte source outputs fail intake."
    )
    prompt_count = $rows.Count
    present_count = $presentCount
    pending_count = $pendingCount
    zero_byte_count = $zeroByteCount
    status_counts = $statusCounts
    kind_counts = $kindCounts
    rows = $rows
}

$payload | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$csvRows = @()
foreach ($row in $rows) {
    $csvRows += [pscustomobject]$row
}
$csvRows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

$lines = @(
    "# Act I Background Source Intake",
    "",
    'Generated by `tools/Export-ActIBackgroundSourceIntake.ps1` from `docs/art/act_i_background_source_prompts.json`.',
    "",
    "Status: $($payload.status). This is source-output intake, not final art acceptance.",
    "",
    "Guardrails:",
    "- Source prompt outputs do not count as final background art.",
    "- Meshy GLBs are helper geometry until imported through Blender and paintover.",
    "- Generated references are paintover references only and must not be imported as room plates.",
    "- Interactive source PSDs require later runtime export and Godot alignment review.",
    "- Zero-byte source outputs fail intake.",
    "",
    "Counts:",
    "- Prompts: $($payload.prompt_count)",
    "- Present source outputs: $presentCount",
    "- Pending source outputs: $pendingCount",
    "- Zero-byte outputs: $zeroByteCount"
)

foreach ($key in @($kindCounts.Keys)) {
    $lines += "- ${key}: $($kindCounts[$key])"
}

$lines += ""

foreach ($roomGroup in @($rows | Group-Object { $_["room_id"] } | Sort-Object @{ Expression = { [int](($_.Group[0]["room_code"]) -replace "\D", "") } })) {
    $roomRows = @($roomGroup.Group)
    $first = $roomRows[0]
    $lines += "## $($first.room_code) - $($first.room_title)"
    $lines += ""
    $lines += "| ID | Kind | Tool | Status | Source | Runtime |"
    $lines += "|---|---|---|---|---|---|"
    foreach ($row in @($roomRows | Sort-Object { $_["kind"] }, { $_["name"] })) {
        $runtime = if ([string]::IsNullOrWhiteSpace([string]$row.runtime_path)) { "-" } else { $row.runtime_path }
        $lines += "| $($row.id) | $($row.kind) | $($row.tool) | $($row.status) | ``$($row.source_path)`` | ``$runtime`` |"
    }
    $lines += ""
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I background source intake JSON -> $jsonPath"
Write-Host "Exported Act I background source intake CSV -> $csvPath"
Write-Host "Exported Act I background source intake report -> $mdPath"
