$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $root "docs\art\act_i_background_manifest.json"
$csvPath = Join-Path $root "docs\art\act_i_background_asset_status.csv"
$reportPath = Join-Path $root "docs\art\act_i_background_asset_status.md"

if (-not (Test-Path -LiteralPath $manifestPath)) {
    throw "Missing Act I background manifest: $manifestPath"
}

$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
$rooms = @($manifest.rooms)
if ($rooms.Count -eq 0) {
    throw "Act I background manifest has no rooms."
}

function Resolve-RepoPath {
    param([Parameter(Mandatory=$true)][string]$RelativePath)

    return Join-Path $root ($RelativePath -replace "/", "\")
}

function Get-AssetContentStatus {
    param(
        [Parameter(Mandatory=$true)][string]$Kind,
        [Parameter(Mandatory=$true)][string]$AbsolutePath,
        [Parameter(Mandatory=$true)][bool]$Exists
    )

    if (-not $Exists) {
        return "missing"
    }

    $item = Get-Item -LiteralPath $AbsolutePath
    if ($item.Length -le 0) {
        return "invalid_empty_file"
    }

    if ($Kind -eq "paintover_source") {
        $bytesToRead = [Math]::Min(4, [int]$item.Length)
        $buffer = New-Object byte[] $bytesToRead
        $stream = [System.IO.File]::OpenRead($AbsolutePath)
        try {
            [void]$stream.Read($buffer, 0, $bytesToRead)
        }
        finally {
            $stream.Dispose()
        }
        $signature = [System.Text.Encoding]::ASCII.GetString($buffer)
        if ($signature -ne "8BPS") {
            return "invalid_psd_signature"
        }
        return "valid_psd_source"
    }

    return "present"
}

$assetRows = New-Object System.Collections.Generic.List[object]
foreach ($room in $rooms) {
    $assetSpecs = @(
        @{ Kind = "blend_blockout"; Path = $room.source_blend; RequiredFor = "Blender greybox" },
        @{ Kind = "paintover_source"; Path = $room.paintover_source; RequiredFor = "Final paintover" },
        @{ Kind = "export_png"; Path = $room.export_png; RequiredFor = "Runtime background source" },
        @{ Kind = "godot_import"; Path = $room.godot_background_resource; RequiredFor = "Godot room integration" }
    )

    foreach ($asset in $assetSpecs) {
        $absolutePath = Resolve-RepoPath $asset.Path
        $exists = Test-Path -LiteralPath $absolutePath
        $sizeBytes = if ($exists) { [int64](Get-Item -LiteralPath $absolutePath).Length } else { 0 }
        $contentStatus = Get-AssetContentStatus -Kind $asset.Kind -AbsolutePath $absolutePath -Exists $exists
        $assetRows.Add([pscustomobject]@{
            room_code = $room.room_code
            room_id = $room.room_id
            title = $room.title
            asset_kind = $asset.Kind
            status = $(if ($exists) { "present" } else { "pending" })
            content_status = $contentStatus
            size_bytes = $sizeBytes
            required_for = $asset.RequiredFor
            relative_path = $asset.Path
        })
    }
}

$assetRows |
    Sort-Object room_code, asset_kind |
    ConvertTo-Csv -NoTypeInformation |
    Set-Content -LiteralPath $csvPath -Encoding UTF8

$presentCount = @($assetRows | Where-Object { $_.status -eq "present" }).Count
$pendingCount = @($assetRows | Where-Object { $_.status -eq "pending" }).Count

$reportLines = @(
    "# Act I Background Asset Status",
    "",
    'Generated by `tools/Export-ActIBackgroundAssetStatus.ps1` from `docs/art/act_i_background_manifest.json`.',
    "",
    "This is a production tracker, not a final-art gate. `pending` means the manifest expects the asset, not that Step 4 is broken.",
    "",
    "Summary: $presentCount present, $pendingCount pending, $($assetRows.Count) total asset slots.",
    "",
    "Rule locks:",
    "- Paintover source PSDs must be real PSD-like files with an 8BPS signature, not text placeholders.",
    "- Empty files never count as valid present assets.",
    "",
    "| Room | Asset | Status | Content Status | Bytes | Required For | Path |",
    "|---|---|---|---|---:|---|---|"
)

foreach ($row in ($assetRows | Sort-Object room_code, asset_kind)) {
    $reportLines += "| $($row.room_code) $($row.title) | $($row.asset_kind) | $($row.status) | $($row.content_status) | $($row.size_bytes) | $($row.required_for) | ``$($row.relative_path)`` |"
}

Set-Content -LiteralPath $reportPath -Value $reportLines -Encoding UTF8

Write-Host "Exported Act I background asset status CSV -> $csvPath"
Write-Host "Exported Act I background asset status report -> $reportPath"
Write-Host "Act I background assets: present=$presentCount, pending=$pendingCount, total=$($assetRows.Count)"
