$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$trackerPath = Join-Path $root "docs\playtest\act_i_review_fix_tracker.json"
$csvPath = Join-Path $root "docs\playtest\act_i_review_decisions_template.csv"
$mdPath = Join-Path $root "docs\playtest\act_i_review_decisions_template.md"

if (-not (Test-Path -LiteralPath $trackerPath)) {
    throw "Missing Act I review fix tracker JSON: $trackerPath"
}

$tracker = Get-Content -LiteralPath $trackerPath -Raw | ConvertFrom-Json
$rooms = @($tracker.rooms)
if ($rooms.Count -ne 11) {
    throw "Act I review decision template expected 11 rooms, got $($rooms.Count)."
}

$rows = @()
foreach ($room in $rooms) {
    $rows += [pscustomobject][ordered]@{
        room_id = $room.room_id
        room_code = $room.room_code
        title = $room.title
        decision = $room.reviewer_decision
        reviewer = $room.reviewer
        reviewed_at = $room.reviewed_at
        decision_note = $room.decision_note
        layout = $room.fix_buckets.layout
        hotspot_readability = $room.fix_buckets.hotspot_readability
        walk_band = $room.fix_buckets.walk_band
        palette_lighting = $room.fix_buckets.palette_lighting
        content_compliance = $room.fix_buckets.content_compliance
        duel_format = $room.fix_buckets.duel_format
        vo_timing_or_pacing = $room.fix_buckets.vo_timing_or_pacing
        risk_tags = (@($room.risk_tags) -join ";")
        critical_hotspots = (@($room.critical_hotspots | ForEach-Object { "$($_.name):$($_.review_status)" }) -join ";")
        close_pairs = (@($room.close_pair_review | ForEach-Object { "$($_.pair):$($_.review_status)" }) -join ";")
    }
}

$rows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

$lines = @(
    "# Act I Review Decision Template",
    "",
    'Generated by `tools/Export-ActIReviewDecisionTemplate.ps1` from `docs/playtest/act_i_review_fix_tracker.json`.',
    "",
    "Purpose: provide a machine-readable batch handoff from human Act I review into the review fix tracker.",
    "",
    "Fill `docs/playtest/act_i_review_decisions_template.csv`, then run the importer first as a dry run:",
    "",
    '```powershell',
    'powershell -NoProfile -ExecutionPolicy Bypass -File tools\Import-ActIReviewDecisions.ps1 -InputCsv docs\playtest\act_i_review_decisions_template.csv -DryRun',
    '```',
    "",
    "Allowed decisions: pending_review, approved, revise_before_art, stop_and_redesign.",
    "",
    "Rules:",
    '- Any non-pending decision must include `reviewer`, `reviewed_at`, and `decision_note`; `reviewed_at` must use `YYYY-MM-DD`.',
    '- `approved` marks the room as paintover-eligible if no start-gate blockers remain.',
    '- `revise_before_art` must include at least one fix bucket note.',
    '- `stop_and_redesign` blocks final paintover until the room is reworked and reviewed again.',
    "- Harbor Registry approval must preserve the accepted Litany/Registrar duel format.",
    "- Harbor Registry non-pending decisions must include a duel_format note confirming the accepted Litany/Registrar duel format remains locked.",
    "- Grey Float non-pending decisions must include a content_compliance note confirming hard-R staging: steam, silhouette, privacy, and agency only.",
    "",
    "| Room | Current Decision | Risk Tags |",
    "|---|---|---|"
)
foreach ($room in $rooms) {
    $lines += "| $($room.room_code) $($room.title) | $($room.reviewer_decision) | $((@($room.risk_tags) -join ', ')) |"
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I review decision CSV template -> $csvPath"
Write-Host "Exported Act I review decision template brief -> $mdPath"
