$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$paintoverPacketPath = Join-Path $root "docs\art\act_i_paintover_packet.json"
$reviewPath = Join-Path $root "docs\playtest\act_i_art_readability_review.md"

if (-not (Test-Path -LiteralPath $paintoverPacketPath)) {
    throw "Missing Act I paintover packet JSON: $paintoverPacketPath"
}

$packet = Get-Content -LiteralPath $paintoverPacketPath -Raw | ConvertFrom-Json
$rooms = @($packet.rooms)
if ($rooms.Count -ne 11) {
    throw "Act I art readability review expected 11 rooms in paintover packet, got $($rooms.Count)."
}

$lines = @(
    "# Act I Art Readability Review",
    "",
    'Generated by `tools/Export-ActIArtReadabilityReview.ps1` from `docs/art/act_i_paintover_packet.json`.',
    "",
    "Purpose: decide whether Act I blockouts are readable enough to start final paintovers, and record exact layout fixes before any room art is locked.",
    "",
    "This is an art/readability review, not a quest-flow proof. Step 4 already proves progression, Rite permutations, and the accepted Registrar duel route.",
    "",
    "Global pass marks:",
    "- Puzzle-critical objects are the brightest readable shapes in the frame.",
    "- Exits read as exits before cursor hover.",
    "- Corvin's side-on walk path remains clear in the y 650-800 band.",
    "- Corvin's live side actions read in context: talk gestures, use reach, and wet brine/drip intent.",
    "- Close hotspot pairs are separable by silhouette, value, local shadow, or prop spacing.",
    "- Wet-verb targets look reachable from Corvin's side-on staging.",
    "- Confession sources read as overheard/discovered truth sources, not as a second Litany UI.",
    "- Grey Float stays hard-R through steam, silhouette, privacy, and labor staging only.",
    "- Registrar art preserves the accepted Litany UI format and does not imply a second confession-spend interface.",
    "",
    "Review result: keep / revise before art / stop and redesign",
    "",
    "Reviewer:",
    "Date:",
    "Build or commit:",
    "Automated report reviewed: yes / no",
    "Contact sheet reviewed: yes / no",
    "Hotspot overlay reviewed: yes / no",
    "Corvin side-action contact sheet reviewed: yes / no",
    "Corvin live verb animations tested in room: yes / no",
    "Paintover packet reviewed: yes / no",
    "Decision CSV date format checked: yes / no (reviewed_at uses YYYY-MM-DD for non-pending decisions)",
    ""
)

foreach ($room in $rooms) {
    $lines += "## $($room.room_code) - $($room.title)"
    $lines += ""
    $lines += "- Blockout: ``$($room.blockout_export)``"
    $lines += "- Overlay: ``$($room.review_overlay)``"
    $lines += "- Paintover source target: ``$($room.paintover_source)`` ($($room.paintover_status))"
    $lines += "- Tone target: $($room.tone)"
    $lines += "- Interaction priorities: $((@($room.interaction_priorities) -join ', '))"
    $lines += ""
    $lines += "Room checks:"
    $lines += "- Brightest puzzle object(s) are correct: yes / mixed / no"
    $lines += "- Walk band is visually clear: yes / mixed / no"
    $lines += "- Exits read without explanation: yes / mixed / no"
    $lines += "- Corvin talk/use/wet side actions read without scale jitter or wrong-facing snaps: yes / mixed / no"
    $lines += "- Palette intent reads correctly: yes / mixed / no"
    $lines += "- Camera/framing should stay locked: yes / mixed / no"

    if ("wet_verb" -in @($room.interaction_priorities)) {
        $lines += "- Wet target reads as reusable verb target: yes / mixed / no"
    }
    if ("confession_source" -in @($room.interaction_priorities)) {
        $lines += "- Confession-source staging reads as overheard/discovered truth, not a duel UI: yes / mixed / no"
    }
    if ("duel" -in @($room.interaction_priorities)) {
        $lines += "- Registrar duel staging preserves accepted Litany format: yes / mixed / no"
    }
    if ($room.room_id -eq "grey_float") {
        $lines += "- Hard-R Float staging stays steam/silhouette/privacy only: yes / mixed / no"
        $lines += "- Amber reads intentionally unsafe, not cozy/safe: yes / mixed / no"
    }

    $lines += ""
    $lines += "Critical hotspot review:"
    if (@($room.critical_hotspots).Count -eq 0) {
        $lines += "- None beyond navigation and room texture."
    } else {
        foreach ($hotspot in @($room.critical_hotspots)) {
            $lines += "- $($hotspot.label) at $($hotspot.position): readable / unclear / move before paint"
        }
    }

    $lines += ""
    $lines += "Close-pair review:"
    if (@($room.close_pair_review).Count -eq 0) {
        $lines += "- None under threshold."
    } else {
        foreach ($note in @($room.close_pair_review)) {
            $lines += "- ${note}: separable / unclear / move before paint"
        }
    }

    $lines += ""
    $lines += "Required fixes before paint:"
    $lines += "- "
    $lines += ""
}

$lines += "## Final Decision"
$lines += ""
$lines += "Proceed to paintovers: yes / no"
$lines += ""
$lines += "Rooms approved without layout changes:"
$lines += "- "
$lines += ""
$lines += "Rooms requiring layout changes before paint:"
$lines += "- "
$lines += ""
$lines += "Duel-format risk found: yes / no"
$lines += "Hard-R content risk found: yes / no"
$lines += "Wet-verb readability risk found: yes / no"
$lines += "Confession-source readability risk found: yes / no"
$lines += ""
$lines += "Decision notes:"
$lines += "- "

Set-Content -LiteralPath $reviewPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I art readability review -> $reviewPath"
