$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $root "docs\art\corvin_animation_manifest.json"
$briefPath = Join-Path $root "docs\art\corvin_animation_brief.md"
$statusCsvPath = Join-Path $root "docs\art\corvin_animation_asset_status.csv"
$statusReportPath = Join-Path $root "docs\art\corvin_animation_asset_status.md"

$variants = @(
    @{ Id = "act_i_clean"; Act = 1; Label = "Act I clean"; Notes = "Recently returned, wet coat, barefoot only until boots pickup; salt only at knuckles." },
    @{ Id = "act_ii_salting"; Act = 2; Label = "Act II salting"; Notes = "No warmth, no taste; visible salt at joints and coat edges." },
    @{ Id = "act_iii_crusted"; Act = 3; Label = "Act III crusted"; Notes = "Memory decay era; crusted silhouette, stiffer hands, worse shoulder asymmetry." }
)

$directions = @("front", "side_right", "back", "side_left")
$animations = @(
    @{ Id = "idle"; Fps = 12; Frames = 12; Loop = $true; Notes = "Ink-on-twos idle with permanent coat drip." },
    @{ Id = "walk"; Fps = 12; Frames = 8; Loop = $true; Notes = "Side profile is production priority; keep root motion measurable and in-place export possible." },
    @{ Id = "talk"; Fps = 12; Frames = 6; Loop = $true; Notes = "Body-only talk cycle; full VO mouth detail remains portrait/face-layer work." },
    @{ Id = "wet"; Fps = 12; Frames = 8; Loop = $false; Notes = "Sleeve shake / drip action for the permanent wet verb." },
    @{ Id = "use"; Fps = 12; Frames = 8; Loop = $false; Notes = "Generic reach/pickup for Act I puzzle items." }
)

$manifest = [ordered]@{
    generated_from = "AGENTS.md sections 5 and 8.3"
    character_id = "corvin"
    character_name = "Corvin Vale"
    pipeline = "Meshy source -> Blender ink/toon render -> 2D sprite sheets"
    runtime_character_scene = "game/characters/corvin/character_corvin.tscn"
    render_fps = 12
    render_scale = "2x target"
    directions = $directions
    variants = @()
}

foreach ($variant in $variants) {
    $animationSpecs = @()
    foreach ($animation in $animations) {
        $directionSpecs = @()
        foreach ($direction in $directions) {
            $directionSpecs += [ordered]@{
                direction = $direction
                source_action = "Corvin_$($variant.Id)_$($animation.Id)_$direction"
                sheet_path = "art/export/characters/corvin/$($variant.Id)/$($animation.Id)_$direction.png"
                godot_resource = "game/characters/corvin/sprites/$($variant.Id)/$($animation.Id)_$direction.png"
            }
        }

        $animationSpecs += [ordered]@{
            id = $animation.Id
            fps = $animation.Fps
            frames = $animation.Frames
            loop = $animation.Loop
            notes = $animation.Notes
            directions = $directionSpecs
        }
    }

    $manifest.variants += [ordered]@{
        id = $variant.Id
        act = $variant.Act
        label = $variant.Label
        notes = $variant.Notes
        meshy_source = "art/src/characters/corvin/meshy/corvin_$($variant.Id).glb"
        blender_source = "art/src/characters/corvin/corvin_$($variant.Id).blend"
        texture_source = "art/src/characters/corvin/textures/corvin_$($variant.Id)_ink.png"
        animations = $animationSpecs
    }
}

$manifest | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

$briefLines = @(
    "# Corvin Animation Manifest",
    "",
    'Generated by `tools/Export-CorvinAnimationManifest.ps1`.',
    "",
    "Pipeline: Meshy source -> Blender ink/toon render -> 2D sprite sheets.",
    "Render contract: 12 fps, 4 directions, 2x target render, deterministic sprite sheets.",
    "Production warning: Corvin has three visual decay variants. This is budgeted here as a real deliverable, not a late polish wish.",
    "",
    "Directions: $($directions -join ', ').",
    "Animations: $(@($animations | ForEach-Object { $_.Id }) -join ', ').",
    ""
)

foreach ($variant in $manifest.variants) {
    $briefLines += "## $($variant.label)"
    $briefLines += ""
    $briefLines += "- Meshy source: ``$($variant.meshy_source)``"
    $briefLines += "- Blender source: ``$($variant.blender_source)``"
    $briefLines += "- Texture source: ``$($variant.texture_source)``"
    $briefLines += "- Notes: $($variant.notes)"
    $briefLines += ""
    $briefLines += "| Animation | FPS | Frames | Loop | Direction Sheets |"
    $briefLines += "|---|---:|---:|---|---|"
    foreach ($animation in $variant.animations) {
        $sheets = @($animation.directions | ForEach-Object { "$($_.direction): ``$($_.sheet_path)``" }) -join "<br>"
        $briefLines += "| $($animation.id) | $($animation.fps) | $($animation.frames) | $($animation.loop) | $sheets |"
    }
    $briefLines += ""
}

Set-Content -LiteralPath $briefPath -Value $briefLines -Encoding UTF8

function Resolve-RepoPath {
    param([Parameter(Mandatory=$true)][string]$RelativePath)
    return Join-Path $root ($RelativePath -replace "/", "\")
}

$statusRows = New-Object System.Collections.Generic.List[object]
foreach ($variant in $manifest.variants) {
    $sourceAssets = @(
        @{ Kind = "meshy_source"; Path = $variant.meshy_source; RequiredFor = "Meshy-to-Blender source" },
        @{ Kind = "blender_source"; Path = $variant.blender_source; RequiredFor = "Deterministic render source" },
        @{ Kind = "texture_source"; Path = $variant.texture_source; RequiredFor = "Ink/toon material source" }
    )

    foreach ($asset in $sourceAssets) {
        $exists = Test-Path -LiteralPath (Resolve-RepoPath $asset.Path)
        $statusRows.Add([pscustomobject]@{
            variant = $variant.id
            animation = ""
            direction = ""
            asset_kind = $asset.Kind
            status = $(if ($exists) { "present" } else { "pending" })
            required_for = $asset.RequiredFor
            relative_path = $asset.Path
        })
    }

    foreach ($animation in $variant.animations) {
        foreach ($directionSpec in $animation.directions) {
            foreach ($asset in @(
                @{ Kind = "sheet_export"; Path = $directionSpec.sheet_path; RequiredFor = "Sprite-sheet export" },
                @{ Kind = "godot_import"; Path = $directionSpec.godot_resource; RequiredFor = "Godot runtime sprite" }
            )) {
                $exists = Test-Path -LiteralPath (Resolve-RepoPath $asset.Path)
                $statusRows.Add([pscustomobject]@{
                    variant = $variant.id
                    animation = $animation.id
                    direction = $directionSpec.direction
                    asset_kind = $asset.Kind
                    status = $(if ($exists) { "present" } else { "pending" })
                    required_for = $asset.RequiredFor
                    relative_path = $asset.Path
                })
            }
        }
    }
}

$statusRows |
    Sort-Object variant, animation, direction, asset_kind |
    ConvertTo-Csv -NoTypeInformation |
    Set-Content -LiteralPath $statusCsvPath -Encoding UTF8

$presentCount = @($statusRows | Where-Object { $_.status -eq "present" }).Count
$pendingCount = @($statusRows | Where-Object { $_.status -eq "pending" }).Count

$statusLines = @(
    "# Corvin Animation Asset Status",
    "",
    'Generated by `tools/Export-CorvinAnimationManifest.ps1` from `docs/art/corvin_animation_manifest.json`.',
    "",
    "This is a production tracker, not a greybox failure. Pending means the contract expects the asset.",
    "",
    "Summary: $presentCount present, $pendingCount pending, $($statusRows.Count) total asset slots.",
    "",
    "| Variant | Animation | Direction | Asset | Status | Path |",
    "|---|---|---|---|---|---|"
)

foreach ($row in ($statusRows | Sort-Object variant, animation, direction, asset_kind)) {
    $statusLines += "| $($row.variant) | $($row.animation) | $($row.direction) | $($row.asset_kind) | $($row.status) | ``$($row.relative_path)`` |"
}

Set-Content -LiteralPath $statusReportPath -Value $statusLines -Encoding UTF8

Write-Host "Exported Corvin animation manifest -> $manifestPath"
Write-Host "Exported Corvin animation brief -> $briefPath"
Write-Host "Exported Corvin animation asset status CSV -> $statusCsvPath"
Write-Host "Exported Corvin animation asset status report -> $statusReportPath"
Write-Host "Corvin animation assets: present=$presentCount, pending=$pendingCount, total=$($statusRows.Count)"
