$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$confessionPath = Join-Path $root "data\confessions.json"
$outDir = Join-Path $root "docs\vo"
$jsonPath = Join-Path $outDir "confession_vo_manifest.json"
$csvPath = Join-Path $outDir "confession_vo_manifest.csv"
$mdPath = Join-Path $outDir "confession_vo_manifest.md"

if (-not (Test-Path -LiteralPath $confessionPath)) {
    throw "Missing confession data: $confessionPath"
}
if (-not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir | Out-Null
}

function Get-WordCount {
    param([string]$Text)
    return [int]([regex]::Matches($Text, "[A-Za-z0-9']+").Count)
}

$confessionData = Get-Content -LiteralPath $confessionPath -Raw -Encoding UTF8 | ConvertFrom-Json
$confessions = @($confessionData | ForEach-Object { $_ })
$rows = @()

foreach ($confession in $confessions | Sort-Object act_available, category, weight, id) {
    foreach ($part in @("confession", "elaboration")) {
        $text = if ($part -eq "confession") { [string]$confession.text } else { [string]$confession.elaboration }
        $suffix = if ($part -eq "confession") { "" } else { "_elaboration" }
        $rows += [pscustomobject][ordered]@{
            line_id = "vo_confession_$($confession.id)$suffix"
            confession_id = [string]$confession.id
            part = $part
            speaker = "CORVIN"
            character = "Corvin Vale"
            text = $text
            word_count = [int](Get-WordCount -Text $text)
            category = [string]$confession.category
            weight = [int]$confession.weight
            act_available = [int]$confession.act_available
            acquisition = [string]$confession.acquisition
            source_file = "data/confessions.json"
            source_ref = "data/confessions.json#$($confession.id)"
            audio_path = "vo/confessions/$($confession.id)$suffix.mp3"
            recording_status = "unrecorded"
            scratch_voice = "Callum"
            scratch_voice_id = "N2lVS1w4EtoT3dr4eOWO"
            rule_note = "Generated from data/confessions.json; do not hand-copy Litany text into Ink."
        }
    }
}

$summaryByCategory = @(
    $confessions |
        Group-Object category |
        Sort-Object Name |
        ForEach-Object {
            $categoryName = $_.Name
            $categoryConfessions = @($_.Group)
            $categoryRows = @($rows | Where-Object { $_.category -eq $categoryName })
            [pscustomobject][ordered]@{
                category = $categoryName
                confession_count = $categoryConfessions.Count
                line_count = $categoryRows.Count
                word_count = ($categoryRows | Measure-Object -Property word_count -Sum).Sum
            }
        }
)

$summaryByAct = @(
    $confessions |
        Group-Object act_available |
        Sort-Object {[int]$_.Name} |
        ForEach-Object {
            $actNumber = [int]$_.Name
            $actConfessions = @($_.Group)
            $actRows = @($rows | Where-Object { [int]$_.act_available -eq $actNumber })
            [pscustomobject][ordered]@{
                act_available = $actNumber
                confession_count = $actConfessions.Count
                line_count = $actRows.Count
                word_count = ($actRows | Measure-Object -Property word_count -Sum).Sum
            }
        }
)

$metadata = [ordered]@{
    generated_from = "data/confessions.json"
    purpose = "Full VO manifest for Litany confession and elaboration lines. This is generated from the confession source of truth, not authored as duplicate Ink text."
    confession_count = $confessions.Count
    line_count = $rows.Count
    word_count = ($rows | Measure-Object -Property word_count -Sum).Sum
    confession_line_count = @($rows | Where-Object { $_.part -eq "confession" }).Count
    elaboration_line_count = @($rows | Where-Object { $_.part -eq "elaboration" }).Count
    recording_status = "unrecorded"
    speaker = "CORVIN"
    scratch_voice = "Callum"
    scratch_voice_id = "N2lVS1w4EtoT3dr4eOWO"
    rule_locks = @(
        "One confession line and one elaboration line are required for every confession.",
        "Audio paths must stay keyed by confession id: vo/confessions/{confession_id}.mp3 and vo/confessions/{confession_id}_elaboration.mp3.",
        "Generated text comes from data/confessions.json; Ink references confession ids only.",
        "Keep the accepted Litany/Registrar duel format and global spend rules."
    )
    categories = $summaryByCategory
    acts = $summaryByAct
    lines = $rows
}

$metadata | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $jsonPath -Encoding UTF8
$rows | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8

$mdLines = @(
    "# Confession VO Manifest",
    "",
    'Generated by `tools/Export-ConfessionVoManifest.ps1` from `data/confessions.json`.',
    "",
    "Purpose: full VO recording plan for Litany confession lines and elaborations. This does not claim shipping audio exists.",
    "",
    "Totals:",
    "- Confessions: $($metadata.confession_count)",
    "- Lines: $($metadata.line_count)",
    "- Words: $($metadata.word_count)",
    "- Confession lines: $($metadata.confession_line_count)",
    "- Elaboration lines: $($metadata.elaboration_line_count)",
    "- Recording status: unrecorded",
    "",
    "Rule locks:",
    "- One confession line and one elaboration line are required for every confession.",
    '- Audio paths must stay keyed by confession id: `vo/confessions/{confession_id}.mp3` and `vo/confessions/{confession_id}_elaboration.mp3`.',
    '- Generated text comes from `data/confessions.json`; Ink references confession ids only.',
    "- Keep the accepted Litany/Registrar duel format and global spend rules.",
    "",
    "## Category Summary",
    "",
    "| Category | Confessions | VO lines | Words |",
    "|---|---:|---:|---:|"
)

foreach ($category in $summaryByCategory) {
    $mdLines += "| $($category.category) | $($category.confession_count) | $($category.line_count) | $($category.word_count) |"
}

$mdLines += ""
$mdLines += "## Act Summary"
$mdLines += ""
$mdLines += "| Act available | Confessions | VO lines | Words |"
$mdLines += "|---:|---:|---:|---:|"
foreach ($act in $summaryByAct) {
    $mdLines += "| $($act.act_available) | $($act.confession_count) | $($act.line_count) | $($act.word_count) |"
}

$mdLines += ""
$mdLines += "## First 20 Lines"
$mdLines += ""
$mdLines += "| ID | Confession | Part | Category | Act | Words | Audio path |"
$mdLines += "|---|---|---|---|---:|---:|---|"
foreach ($row in @($rows | Select-Object -First 20)) {
    $confessionId = [string]$row.confession_id
    $audioPath = [string]$row.audio_path
    $mdLines += "| $($row.line_id) | ``$confessionId`` | $($row.part) | $($row.category) | $($row.act_available) | $($row.word_count) | ``$audioPath`` |"
}

Set-Content -LiteralPath $mdPath -Value $mdLines -Encoding UTF8

Write-Host "Exported confession VO manifest JSON -> $jsonPath"
Write-Host "Exported confession VO manifest CSV -> $csvPath"
Write-Host "Exported confession VO manifest report -> $mdPath"
Write-Host "Confession VO manifest: confessions=$($metadata.confession_count), lines=$($metadata.line_count), words=$($metadata.word_count)"
