$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$imagePath = "docs/art/reference/look_targets/act_i_harbor_look_target_v1.png"
$jsonPath = Join-Path $root "docs\art\act_i_look_target_reference.json"
$mdPath = Join-Path $root "docs\art\act_i_look_target_reference.md"
$absoluteImagePath = Join-Path $root ($imagePath -replace "/", "\")

if (-not (Test-Path -LiteralPath $absoluteImagePath -PathType Leaf)) {
    throw "Missing Act I look target image: $imagePath"
}

$imageItem = Get-Item -LiteralPath $absoluteImagePath
if ($imageItem.Length -le 0) {
    throw "Act I look target image is zero-byte: $imagePath"
}

Add-Type -AssemblyName System.Drawing
$image = [System.Drawing.Image]::FromFile($absoluteImagePath)
try {
    $width = [int]$image.Width
    $height = [int]$image.Height
}
finally {
    $image.Dispose()
}

$payload = [ordered]@{
    status = "reference_only_review_target"
    generated_from = "chat imagegen preview"
    image_path = $imagePath
    width = $width
    height = $height
    size_bytes = [int64]$imageItem.Length
    purpose = "Act I mood, palette, staging, and side-on adventure-game readability reference."
    strengths_to_preserve = @(
        "side-on Corvin staging",
        "wet black coat silhouette",
        "barefoot drowned read",
        "amber living warmth versus absinthe wrong-light contrast",
        "leviathan rib architecture",
        "bottom verb/inventory strip scale",
        "walkable harbor foreground"
    )
    production_limits = @(
        "not a final room plate",
        "not a paintover approval",
        "not a source of hotspot coordinates",
        "not a replacement for Blender greybox perspective",
        "not a diffusion-per-frame character source",
        "too detailed for direct sprite-scale production"
    )
    guardrails = @(
        "Use this only as a look target during human review and paintover direction.",
        "Blender greybox and paintover remain authoritative for final Act I backgrounds.",
        "Generated images remain reference only and must not be imported as finished room plates.",
        "Corvin production animation must stay deterministic 3D-to-Blender-to-2D, not diffusion-per-frame.",
        "All final room exports still need G9/G10 palette checks.",
        "Do not start final paintovers while the start gate reports blocked_pending_human_review."
    )
}

$payload | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$lines = @(
    "# Act I Look Target Reference",
    "",
    'Generated by `tools/Export-ActILookTargetReference.ps1` from the preview image saved at `docs/art/reference/look_targets/act_i_harbor_look_target_v1.png`.',
    "",
    "Status: reference_only_review_target.",
    "Image: ``$imagePath``",
    "Dimensions: $($width)x$($height)",
    "Size bytes: $($imageItem.Length)",
    "",
    "Purpose: Act I mood, palette, staging, and side-on adventure-game readability reference.",
    "",
    "Use During Review:",
    "- Compare blockout contact sheets against this for silhouette strength, foreground walkability, and amber/green lighting logic.",
    "- Preserve the side-on Corvin read, wet black coat silhouette, barefoot drowned read, leviathan rib architecture, and bottom verb/inventory strip scale.",
    "- Treat the image as a mood/readability target only, not production source art.",
    "",
    "Production Limits:",
    "- Not a final room plate.",
    "- Not a paintover approval.",
    "- Not a source of hotspot coordinates.",
    "- Not a replacement for Blender greybox perspective.",
    "- Not a diffusion-per-frame character source.",
    "- Too detailed for direct sprite-scale production.",
    "",
    "Guardrails:",
    "- Use this only as a look target during human review and paintover direction.",
    "- Blender greybox and paintover remain authoritative for final Act I backgrounds.",
    "- Generated images remain reference only and must not be imported as finished room plates.",
    "- Corvin production animation must stay deterministic 3D-to-Blender-to-2D, not diffusion-per-frame.",
    "- All final room exports still need G9/G10 palette checks.",
    "- Do not start final paintovers while the start gate reports blocked_pending_human_review."
)

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Act I look target reference JSON -> $jsonPath"
Write-Host "Exported Act I look target reference report -> $mdPath"
Write-Host "Act I look target reference: status=$($payload.status), image=$($width)x$($height), bytes=$($imageItem.Length)."
