$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$workOrderPath = Join-Path $root "docs\art\corvin_side_priority_work_order.json"
$jsonPath = Join-Path $root "docs\art\corvin_side_action_scaffold.json"
$mdPath = Join-Path $root "docs\art\corvin_side_action_scaffold.md"
$actionDir = Join-Path $root "art\src\characters\corvin\actions\act_i_clean"
$sourceBlend = "art/src/characters/corvin/corvin_act_i_clean.blend"
$shaderBlend = "art/src/shaders/ink_wash_shader_spike.blend"

if (-not (Test-Path -LiteralPath $workOrderPath)) {
    throw "Missing Corvin side action scaffold input: $workOrderPath"
}

$workOrderPayload = Get-Content -LiteralPath $workOrderPath -Raw | ConvertFrom-Json
$sideSheetSpecs = $workOrderPayload.side_sheet_specs
if ($null -eq $sideSheetSpecs) {
    throw "Corvin side action scaffold requires side_sheet_specs in $workOrderPath."
}

foreach ($repoRelative in @($sourceBlend, $shaderBlend)) {
    $absolute = Join-Path $root ($repoRelative -replace "/", "\")
    if (-not (Test-Path -LiteralPath $absolute)) {
        throw "Missing Corvin side action scaffold source: $repoRelative"
    }
}

New-Item -ItemType Directory -Force -Path $actionDir | Out-Null

$expectedAnimations = @("talk", "use", "wet")
$actions = New-Object System.Collections.Generic.List[object]

foreach ($animation in $expectedAnimations) {
    $spec = $sideSheetSpecs.$animation
    if ($null -eq $spec) {
        throw "Corvin side action scaffold missing side_sheet_specs.$animation."
    }

    $loop = $animation -eq "talk"
    $frames = @($spec.frame_beats).Count
    $actionId = "act_i_clean_${animation}_side"
    $sheetTargets = @(
        "art/export/characters/corvin/act_i_clean/${animation}_side_right.png",
        "art/export/characters/corvin/act_i_clean/${animation}_side_left.png"
    )
    $godotTargets = @(
        "game/characters/corvin/sprites/act_i_clean/${animation}_side_right.png",
        "game/characters/corvin/sprites/act_i_clean/${animation}_side_left.png"
    )

    $sheetStatus = "pending"
    foreach ($target in $sheetTargets + $godotTargets) {
        $absoluteTarget = Join-Path $root ($target -replace "/", "\")
        if (Test-Path -LiteralPath $absoluteTarget) {
            $sheetStatus = "render_or_import_exists_review_required"
        }
    }

    $actionPayload = [ordered]@{
        action_id = $actionId
        variant = "act_i_clean"
        animation = $animation
        directions = @("side_right", "side_left")
        fps = 12
        frames = $frames
        loop = $loop
        blender_action = [string]$spec.blender_action
        source_blend = $sourceBlend
        shader_blend = $shaderBlend
        source_basis = [string]$spec.source_basis
        motion_intent = [string]$spec.motion_intent
        mirror_policy = [string]$spec.mirror_policy
        frame_beats = @($spec.frame_beats)
        acceptance_checks = @($spec.acceptance_checks)
        sheet_export_targets = $sheetTargets
        godot_import_targets = $godotTargets
        sheet_status = $sheetStatus
        scaffold_status = "source_action_scaffold_ready_pending_render"
        rule_locks = @(
            "No PNG sheet is created by this scaffold.",
            "Do not create diffusion-per-frame production art.",
            "Use the canonical Act I clean Blender source.",
            "Preserve current side idle registration for first and final frames."
        )
    }

    $actions.Add([pscustomobject]$actionPayload)

    $actionLines = @(
        "# Corvin $animation Side Action Scaffold",
        "",
        'Generated by `tools/Export-CorvinSideActionScaffold.ps1`.',
        "",
        "Status: source_action_scaffold_ready_pending_render",
        "This file is an animator and Blender handoff. No PNG sheet is created by this scaffold.",
        "",
        ('- Action id: `{0}`' -f $actionId),
        ('- Blender action: `{0}`' -f $spec.blender_action),
        '- Variant: `act_i_clean`',
        '- Directions: `side_right`, `side_left`',
        "- Frames: $frames at 12 fps",
        "- Loop: $loop",
        ('- Source blend: `{0}`' -f $sourceBlend),
        ('- Shader blend: `{0}`' -f $shaderBlend),
        "- Purpose: $($spec.purpose)",
        "- Source basis: $($spec.source_basis)",
        "- Motion intent: $($spec.motion_intent)",
        "- Mirror policy: $($spec.mirror_policy)",
        "",
        "Frame beats:"
    )
    foreach ($beat in @($spec.frame_beats)) {
        $actionLines += "- $beat"
    }
    $actionLines += @(
        "",
        "Acceptance checks:"
    )
    foreach ($check in @($spec.acceptance_checks)) {
        $actionLines += "- $check"
    }
    $actionLines += @(
        "",
        "Sheet export targets:"
    )
    foreach ($target in $sheetTargets) {
        $actionLines += ('- `{0}`' -f $target)
    }
    $actionLines += @(
        "",
        "Godot import targets:"
    )
    foreach ($target in $godotTargets) {
        $actionLines += ('- `{0}`' -f $target)
    }
    $actionLines += @(
        "",
        "Rule locks:",
        "- No PNG sheet is created by this scaffold.",
        "- Do not create diffusion-per-frame production art.",
        "- Do not mark this animation as final polish until rendered, imported, and reviewed in Godot."
    )

    Set-Content -LiteralPath (Join-Path $actionDir "$animation`_side.action.md") -Value $actionLines -Encoding UTF8
}

$payload = [ordered]@{
    generated_from = "docs/art/corvin_side_priority_work_order.json"
    purpose = "Concrete Blender action handoff for the next Act I side-view Corvin sheets before rendering talk/use/wet."
    status = "source_action_scaffold_ready_pending_render"
    source_blend = $sourceBlend
    shader_blend = $shaderBlend
    created_sheet_exports = 0
    created_godot_imports = 0
    rule_locks = @(
        "No PNG sheet is created by this scaffold.",
        "Do not create diffusion-per-frame production art.",
        "Side talk/use/wet remain pending until deterministic Blender sheets exist.",
        "The wet action must read as physical brine, not magic."
    )
    actions = @($actions.ToArray())
}

$payload | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$lines = @(
    "# Corvin Side Action Scaffold",
    "",
    'Generated by `tools/Export-CorvinSideActionScaffold.ps1`.',
    "",
    "Purpose: concrete animator and Blender action handoff for the next Act I side-view Corvin sheets.",
    "",
    "Status: source_action_scaffold_ready_pending_render",
    "No PNG sheet is created by this scaffold.",
    "Created sheet exports: 0",
    "Created Godot imports: 0",
    "",
    "Sources:",
    ('- Source blend: `{0}`' -f $sourceBlend),
    ('- Shader blend: `{0}`' -f $shaderBlend),
    "",
    "Rule locks:",
    "- Do not create diffusion-per-frame production art.",
    "- Side talk/use/wet remain pending until deterministic Blender sheets exist.",
    "- The wet action must read as physical brine, not magic.",
    "",
    "Actions:"
)

foreach ($action in @($actions.ToArray())) {
    $lines += @(
        "",
        "## $($action.animation)",
        ('- Action id: `{0}`' -f $action.action_id),
        ('- Blender action: `{0}`' -f $action.blender_action),
        "- Frames: $($action.frames) at $($action.fps) fps",
        "- Loop: $($action.loop)",
        "- Scaffold status: $($action.scaffold_status)",
        "- Sheet status: $($action.sheet_status)",
        "- Motion intent: $($action.motion_intent)",
        "- Mirror policy: $($action.mirror_policy)",
        "- Frame beats:"
    )
    foreach ($beat in @($action.frame_beats)) {
        $lines += "  - $beat"
    }
    $lines += "- Acceptance checks:"
    foreach ($check in @($action.acceptance_checks)) {
        $lines += "  - $check"
    }
    $lines += "- Sheet export targets:"
    foreach ($target in @($action.sheet_export_targets)) {
        $lines += ('  - `{0}`' -f $target)
    }
    $lines += "- Godot import targets:"
    foreach ($target in @($action.godot_import_targets)) {
        $lines += ('  - `{0}`' -f $target)
    }
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding UTF8

Write-Host "Exported Corvin side action scaffold JSON -> $jsonPath"
Write-Host "Exported Corvin side action scaffold report -> $mdPath"
Write-Host "Exported Corvin side action handoffs -> $actionDir"
Write-Host "Corvin side action scaffold: actions=$($actions.Count), createdSheetExports=0, createdGodotImports=0"
