from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "docs" / "art" / "act_i_openai_standees.json"
REPORT_PATH = ROOT / "docs" / "art" / "act_i_standee_color_grade.md"
CONTACT_PATH = ROOT / "docs" / "art" / "review" / "act_i_openai_standees_contact_sheet.png"

CHARACTER_PALETTE = (
    (0x0C, 0x10, 0x13),
    (0x2A, 0x3A, 0x40),
    (0xE4, 0xDC, 0xC8),
    (0xC9, 0x8A, 0x3C),
)

STANDEE_NAMES = {
    "registrar": "The Registrar",
    "juno": "Juno Ash",
    "prosper": "Half-Coin Prosper",
    "tomas_bollard": "Bollard-of-Tomas",
    "sabine": "Sabine Croix",
    "teodor": "Brother Teodor",
    "bone_chandler": "The Bone Chandler",
    "market_crowd": "Salt Market Crowd",
}


def nearest_character_color(r: int, g: int, b: int) -> tuple[int, int, int]:
    return min(
        CHARACTER_PALETTE,
        key=lambda color: (r - color[0]) ** 2 + (g - color[1]) ** 2 + (b - color[2]) ** 2,
    )


def grade_pixel(r: int, g: int, b: int, a: int) -> tuple[int, int, int, int]:
    if a <= 16:
        return r, g, b, a

    # Standees are characters, not wrong-light props. Generated sheets can use
    # the locked absinthe slot as a generic highlight, which reads sickly green
    # once placed over the room plates. Re-home those pixels into warm oil-light
    # or dull cloth shadow and reserve green for the backgrounds/set dressing.
    if (r, g, b) == (0x7D, 0x9B, 0x4E):
        return 0xC9, 0x8A, 0x3C, a

    # Repair previously graded absinthe highlights when this script is rerun
    # without re-importing the raw sheets first.
    if 95 <= r <= 150 and 82 <= g <= 125 and 50 <= b <= 92 and r >= g and g > b:
        return 0xC9, 0x8A, 0x3C, a

    # Keep shadow structure, but stop green-lit faces and coats from reading as
    # separate wrong-light art when composited over amber/slate room plates.
    if g > r * 1.08 and g > b * 1.03 and g > 54:
        luminance = int(round((r * 0.30) + (g * 0.52) + (b * 0.18)))
        r = int(round((r * 0.45) + (luminance * 0.38) + 14))
        g = int(round((g * 0.38) + (luminance * 0.44) + 4))
        b = int(round((b * 0.52) + (luminance * 0.28)))

    # Pull all opaque standee pixels slightly toward the room's slate/amber bias.
    if max(r, g, b) > 86:
        r = int(round(r * 1.04 + 5))
        g = int(round(g * 0.91))
        b = int(round(b * 0.92))
    else:
        r = int(round(r * 0.96))
        g = int(round(g * 0.91))
        b = int(round(b * 0.96))

    r, g, b = max(0, min(255, r)), max(0, min(255, g)), max(0, min(255, b))
    r, g, b = nearest_character_color(r, g, b)
    return r, g, b, a


def greenish_percent(image: Image.Image) -> float:
    pixels = list(image.convert("RGBA").getdata())
    opaque = [px for px in pixels if px[3] > 16]
    if not opaque:
        return 0.0
    greenish = sum(1 for r, g, b, _a in opaque if g > r * 1.12 and g > b * 1.05 and g > 70)
    return (greenish / len(opaque)) * 100.0


def make_contact_sheet(paths: list[Path]) -> Image.Image:
    thumb_w, thumb_h = 360, 300
    pad = 28
    label_h = 44
    columns = 4
    rows = 2
    canvas = Image.new(
        "RGB",
        (columns * thumb_w + (columns + 1) * pad, rows * (thumb_h + label_h) + (rows + 1) * pad),
        (12, 16, 19),
    )
    draw = ImageDraw.Draw(canvas)
    for index, path in enumerate(paths):
        image = Image.open(path).convert("RGBA")
        image.thumbnail((thumb_w, thumb_h), Image.Resampling.LANCZOS)
        col = index % columns
        row = index // columns
        x = pad + col * (thumb_w + pad)
        y = pad + row * (thumb_h + label_h + pad)
        back = Image.new("RGBA", (thumb_w, thumb_h), (42, 58, 64, 255))
        back.alpha_composite(image, ((thumb_w - image.width) // 2, thumb_h - image.height))
        canvas.paste(back.convert("RGB"), (x, y))
        label = STANDEE_NAMES.get(path.stem, path.stem.replace("_", " ").title())
        draw.text((x, y + thumb_h + 8), label, fill=(228, 220, 200))
    return canvas


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    entries = manifest["standees"]
    lines = [
        "# Act I Standee Color Grade",
        "",
        "Generated by `tools/Grade-ActIStandees.py`.",
        "",
        "Purpose: reduce green-biased generated standee pixels so named characters sit inside the Act I wet-black/slate/bone/amber room plates.",
        "",
        "The grade is idempotent: it reads each raw alpha export and rewrites the runtime PNG, so repeated runs do not compound color shifts.",
        "Runtime standees are locked to wet black, harbor slate, bone white, and whale-oil amber. Absinthe green is reserved for room wrong-light and is not allowed on character standees.",
        "",
        "| Standee | Greenish before | Greenish after |",
        "|---|---:|---:|",
    ]

    runtime_paths: list[Path] = []
    for entry in entries:
        raw_path = ROOT / entry["raw_export"]
        runtime_path = ROOT / entry["game_resource"]
        image = Image.open(raw_path).convert("RGBA")
        before = greenish_percent(image)
        graded = Image.new("RGBA", image.size)
        graded.putdata([grade_pixel(*px) for px in image.getdata()])
        after = greenish_percent(graded)
        runtime_path.parent.mkdir(parents=True, exist_ok=True)
        graded.save(runtime_path, optimize=True)
        runtime_paths.append(runtime_path)
        lines.append(f"| `{runtime_path.name}` | {before:.1f}% | {after:.1f}% |")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    CONTACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    make_contact_sheet(runtime_paths).save(CONTACT_PATH)
    print(f"graded={len(runtime_paths)}")
    print(f"report={REPORT_PATH.relative_to(ROOT)}")
    print(f"contact={CONTACT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
