from __future__ import annotations

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
STANDEE_DIR = ROOT / "game" / "standees" / "act_i"
REPORT_PATH = ROOT / "docs" / "art" / "act_i_standee_color_grade.md"


def grade_pixel(r: int, g: int, b: int, a: int) -> tuple[int, int, int, int]:
    if a <= 16:
        return r, g, b, a

    # Keep shadow structure, but stop green-lit faces and coats from reading as
    # separate wrong-light art when composited over amber/slate room plates.
    if g > r * 1.08 and g > b * 1.03 and g > 54:
        luminance = int(round((r * 0.30) + (g * 0.52) + (b * 0.18)))
        r = int(round((r * 0.45) + (luminance * 0.38) + 14))
        g = int(round((g * 0.38) + (luminance * 0.44) + 4))
        b = int(round((b * 0.52) + (luminance * 0.28)))

    # Pull all opaque standee pixels slightly toward the room's slate/amber bias.
    if max(r, g, b) > 86:
        r = int(round(r * 1.04 + 5))
        g = int(round(g * 0.91))
        b = int(round(b * 0.92))
    else:
        r = int(round(r * 0.96))
        g = int(round(g * 0.91))
        b = int(round(b * 0.96))

    return max(0, min(255, r)), max(0, min(255, g)), max(0, min(255, b)), a


def greenish_percent(image: Image.Image) -> float:
    pixels = list(image.convert("RGBA").getdata())
    opaque = [px for px in pixels if px[3] > 16]
    if not opaque:
        return 0.0
    greenish = sum(1 for r, g, b, _a in opaque if g > r * 1.12 and g > b * 1.05 and g > 70)
    return (greenish / len(opaque)) * 100.0


def main() -> None:
    lines = [
        "# Act I Standee Color Grade",
        "",
        "Generated by `tools/Grade-ActIStandees.py`.",
        "",
        "Purpose: reduce green-biased generated standee pixels so named characters sit inside the Act I wet-black/slate/bone/amber room plates.",
        "",
        "| Standee | Greenish before | Greenish after |",
        "|---|---:|---:|",
    ]

    for path in sorted(STANDEE_DIR.glob("*.png")):
        image = Image.open(path).convert("RGBA")
        before = greenish_percent(image)
        graded = Image.new("RGBA", image.size)
        graded.putdata([grade_pixel(*px) for px in image.getdata()])
        after = greenish_percent(graded)
        graded.save(path, optimize=True)
        lines.append(f"| `{path.name}` | {before:.1f}% | {after:.1f}% |")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"graded={len(list(STANDEE_DIR.glob('*.png')))}")
    print(f"report={REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
