from __future__ import annotations

import json
import argparse
from colorsys import rgb_to_hsv
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
STANDEE_DIR = ROOT / "game" / "standees" / "act_i"
REPORT_JSON = ROOT / "docs" / "art" / "act_i_character_palette_grade.json"
REPORT_MD = ROOT / "docs" / "art" / "act_i_character_palette_grade.md"

SLATE = (42, 58, 64)
AMBER = (201, 138, 60)
BONE = (228, 220, 200)


def clamp(value: float) -> int:
    return max(0, min(255, round(value)))


def green_cast_ratio(image: Image.Image) -> float:
    total = 0
    green = 0
    for r, g, b, a in image.convert("RGBA").getdata():
        if a <= 8:
            continue
        total += 1
        h, s, v = rgb_to_hsv(r / 255, g / 255, b / 255)
        hue = h * 360.0
        if 70.0 <= hue <= 170.0 and s > 0.10 and v > 0.03:
            green += 1
    return (green / max(1, total)) * 100.0


def grade_pixel(r: int, g: int, b: int, a: int) -> tuple[int, int, int, int]:
    if a <= 8:
        return r, g, b, a

    h, s, v = rgb_to_hsv(r / 255, g / 255, b / 255)
    hue = h * 360.0
    luminance = (r * 0.30) + (g * 0.52) + (b * 0.18)

    if 70.0 <= hue <= 170.0 and s > 0.08:
        if luminance >= 112:
            target = AMBER
            blend = 0.30
        elif luminance >= 74:
            target = (
                (SLATE[0] * 0.55) + (AMBER[0] * 0.45),
                (SLATE[1] * 0.55) + (AMBER[1] * 0.45),
                (SLATE[2] * 0.55) + (AMBER[2] * 0.45),
            )
            blend = 0.26
        else:
            target = SLATE
            blend = 0.42
        r = clamp((r * (1.0 - blend)) + (target[0] * blend))
        g = clamp((g * (1.0 - blend)) + (target[1] * blend) - 4)
        b = clamp((b * (1.0 - blend)) + (target[2] * blend))
    elif 170.0 < hue <= 215.0 and s > 0.12:
        target = SLATE
        blend = 0.20
        r = clamp((r * (1.0 - blend)) + (target[0] * blend))
        g = clamp((g * (1.0 - blend)) + (target[1] * blend))
        b = clamp((b * (1.0 - blend)) + (target[2] * blend))

    # Transparent edges picked up green halos from generated cutouts. Warm them
    # slightly so subpixel fringes sit on amber/slate plates instead of glowing.
    if a < 190 and g > r and g >= b:
        r = clamp(r + 10)
        g = clamp(g - 8)
        b = clamp(b - 2)

    return r, g, b, a


def analyze_image(path: Path) -> dict[str, object]:
    image = Image.open(path).convert("RGBA")
    return {
        "asset": path.relative_to(ROOT).as_posix(),
        "width": image.width,
        "height": image.height,
        "green_cast_percent": round(green_cast_ratio(image), 2),
    }


def grade_image(path: Path) -> dict[str, object]:
    before = Image.open(path).convert("RGBA")
    before_ratio = green_cast_ratio(before)
    out = Image.new("RGBA", before.size, (0, 0, 0, 0))
    out.putdata([grade_pixel(*pixel) for pixel in before.getdata()])
    after_ratio = green_cast_ratio(out)
    out.save(path, optimize=True)
    return {
        "asset": path.relative_to(ROOT).as_posix(),
        "width": before.width,
        "height": before.height,
        "green_cast_percent_before": round(before_ratio, 2),
        "green_cast_percent_after": round(after_ratio, 2),
        "green_cast_delta": round(before_ratio - after_ratio, 2),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit or apply the Act I standee palette grade.")
    parser.add_argument("--apply", action="store_true", help="Rewrite standee PNGs with the palette grade.")
    args = parser.parse_args()

    source_paths = sorted(STANDEE_DIR.glob("*.png"))
    records = [grade_image(path) for path in source_paths] if args.apply else []
    analysis_records = [analyze_image(path) for path in source_paths]
    report = {
        "status": "graded" if args.apply else "audited",
        "asset_count": len(records),
        "current_asset_count": len(analysis_records),
        "palette_rule": "Act I character overlays keep green reserved for wrong light; standee shadows are biased toward harbor slate and whale-oil amber.",
        "records": records,
        "current_assets": analysis_records,
    }
    REPORT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Act I Character Palette Grade",
        "",
        "Generated by `tools/Grade-ActICharacterPalette.py`.",
        "",
        "This pass reduces generated green/teal cast on Act I character standees while preserving harbor-slate shadow and whale-oil amber highlights.",
        "",
        f"- Mode: `{'apply' if args.apply else 'audit'}`",
    ]
    if records:
        lines.extend(
            [
                "",
                "| Asset | Green cast before | Green cast after | Delta |",
                "|---|---:|---:|---:|",
            ]
        )
        for record in records:
            lines.append(
                f"| `{record['asset']}` | {record['green_cast_percent_before']}% | "
                f"{record['green_cast_percent_after']}% | {record['green_cast_delta']}% |"
            )
    lines.extend(
        [
            "",
            "## Current Assets",
            "",
            "| Asset | Green cast |",
            "|---|---:|",
        ]
    )
    for record in analysis_records:
        lines.append(f"| `{record['asset']}` | {record['green_cast_percent']}% |")
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"mode={'apply' if args.apply else 'audit'}")
    print(f"graded_standees={len(records)}")
    print(f"audited_standees={len(analysis_records)}")
    print(f"report={REPORT_JSON.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
