$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$mapPath = Join-Path $root "docs\art\act_i_hotspot_map.csv"
$overlayPath = Join-Path $root "docs\art\act_i_hotspot_overlay.svg"
$layoutAuditPath = Join-Path $root "docs\art\act_i_hotspot_layout_audit.md"

powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot "Export-ActIHotspotMap.ps1")

if (-not (Test-Path -LiteralPath $mapPath)) {
    throw "Missing Act I hotspot map export: $mapPath"
}

$rows = @(Import-Csv -LiteralPath $mapPath)
if ($rows.Count -ne 69) {
    throw "Act I hotspot map row count mismatch: expected 69, got $($rows.Count)"
}

$requiredColumns = @(
    "room_id",
    "room_code",
    "room_title",
    "type",
    "name",
    "label",
    "x",
    "y",
    "target_room",
    "requires_items",
    "requires_flags",
    "items_add",
    "flags_set",
    "confessions_discover",
    "ink_knot",
    "wet_ink_knot",
    "blocked_ink_knot",
    "alternate_requires_flags",
    "alternate_flags_set",
    "alternate_ink_knot",
    "duel_opponent"
)

$actualColumns = @($rows[0].PSObject.Properties.Name)
foreach ($column in $requiredColumns) {
    if ($column -notin $actualColumns) {
        throw "Act I hotspot map is missing required column: $column"
    }
}

$stageWidth = 1920
$stageHeight = 1080
$closeDistance = 90
$positionedRows = @()
$coordinateErrors = @()

foreach ($row in $rows) {
    $x = 0.0
    $y = 0.0
    $hasX = [double]::TryParse($row.x, [ref]$x)
    $hasY = [double]::TryParse($row.y, [ref]$y)

    if (-not $hasX -or -not $hasY) {
        $coordinateErrors += "$($row.room_id)/$($row.name) has non-numeric coordinates: x='$($row.x)', y='$($row.y)'"
        continue
    }

    if ($x -lt 0 -or $x -gt $stageWidth -or $y -lt 0 -or $y -gt $stageHeight) {
        $coordinateErrors += "$($row.room_id)/$($row.name) is outside ${stageWidth}x${stageHeight}: x=$x, y=$y"
    }

    $positionedRows += [pscustomobject]@{
        RoomId = $row.room_id
        Name = $row.name
        Type = $row.type
        X = $x
        Y = $y
    }
}

if ($coordinateErrors.Count -gt 0) {
    throw "Act I hotspot coordinate validation failed:`n$($coordinateErrors -join "`n")"
}

$closePairs = @()
foreach ($roomGroup in ($positionedRows | Group-Object RoomId)) {
    $roomRows = @($roomGroup.Group)
    for ($i = 0; $i -lt $roomRows.Count; $i++) {
        for ($j = $i + 1; $j -lt $roomRows.Count; $j++) {
            $a = $roomRows[$i]
            $b = $roomRows[$j]
            $dx = $a.X - $b.X
            $dy = $a.Y - $b.Y
            $distance = [math]::Sqrt(($dx * $dx) + ($dy * $dy))
            if ($distance -lt $closeDistance) {
                $closePairs += [pscustomobject]@{
                    RoomId = $roomGroup.Name
                    A = $a.Name
                    B = $b.Name
                    Distance = [math]::Round($distance, 1)
                    AX = [math]::Round($a.X, 1)
                    AY = [math]::Round($a.Y, 1)
                    BX = [math]::Round($b.X, 1)
                    BY = [math]::Round($b.Y, 1)
                }
            }
        }
    }
}

$auditLines = @(
    "# Act I Hotspot Layout Audit",
    "",
    'Generated by `tools/Validate-ActIHotspotMap.ps1` from `docs/art/act_i_hotspot_map.csv`.',
    "",
    "Stage: ${stageWidth}x${stageHeight}",
    "Bounds: pass - $($positionedRows.Count) positioned rows are numeric and inside the stage.",
    "Close-pair review threshold: ${closeDistance}px.",
    "",
    "## Close-Pair Review",
    "",
    "These are warnings, not gate failures. Some dense clusters are intentional for side-on adventure-game staging, but final art should leave each cluster visually separable."
)

if ($closePairs.Count -eq 0) {
    $auditLines += ""
    $auditLines += "No same-room hotspot pairs are closer than ${closeDistance}px."
} else {
    $auditLines += ""
    $auditLines += "| Room | Hotspot A | Hotspot B | Distance | A | B |"
    $auditLines += "|---|---|---|---:|---|---|"
    foreach ($pair in ($closePairs | Sort-Object RoomId, Distance, A, B)) {
        $auditLines += "| $($pair.RoomId) | $($pair.A) | $($pair.B) | $($pair.Distance)px | $($pair.AX), $($pair.AY) | $($pair.BX), $($pair.BY) |"
    }
}

Set-Content -LiteralPath $layoutAuditPath -Value $auditLines -Encoding UTF8

$expectedRoomCounts = @{
    almshouse = 5
    bone_chandler = 5
    church_of_the_drowned = 6
    fish_hall = 5
    grey_float = 7
    harbor_registry = 6
    harbormaster_office = 5
    mudflats = 7
    old_quay = 9
    sabine_office = 2
    salt_market = 12
}

foreach ($roomId in $expectedRoomCounts.Keys) {
    $count = @($rows | Where-Object { $_.room_id -eq $roomId }).Count
    if ($count -ne $expectedRoomCounts[$roomId]) {
        throw "Act I hotspot map count mismatch for ${roomId}: expected $($expectedRoomCounts[$roomId]), got $count"
    }
}

function Require-Row {
    param(
        [Parameter(Mandatory=$true)]
        [scriptblock]$Predicate,
        [Parameter(Mandatory=$true)]
        [string]$Description
    )

    $match = @($rows | Where-Object $Predicate)
    if ($match.Count -ne 1) {
        throw "Act I hotspot map expected exactly one row for $Description, got $($match.Count)"
    }
    return $match[0]
}

$registrar = Require-Row { $_.room_id -eq "harbor_registry" -and $_.name -eq "Registrar" } "Registrar duel hotspot"
if ($registrar.type -ne "duel" -or $registrar.duel_opponent -ne "registrar") {
    throw "Registrar hotspot export does not preserve duel metadata."
}
if ($registrar.requires_flags -ne "FL_manifest_known") {
    throw "Registrar hotspot export does not preserve the FL_manifest_known gate."
}
if ($registrar.flags_set -ne "FL_rite_name|FL_registrar_sold_manifest") {
    throw "Registrar hotspot export does not preserve Rite/Act II hook flags."
}

$tomas = Require-Row { $_.room_id -eq "old_quay" -and $_.name -eq "Tomas" } "Old Quay Tomas hotspot"
if ($tomas.alternate_requires_flags -ne "FL_bollard_petra_seen|FL_bollard_ledger_seen|FL_bollard_bride_seen") {
    throw "Tomas hotspot export does not preserve all-three-bollards prerequisites."
}
if ($tomas.alternate_flags_set -ne "FL_bollard_row_reported" -or $tomas.alternate_ink_knot -ne "old_quay_bollards_all_seen") {
    throw "Tomas hotspot export does not preserve all-three-bollards alternate result."
}

$wetRows = @($rows | Where-Object { -not [string]::IsNullOrWhiteSpace($_.wet_ink_knot) })
if ($wetRows.Count -ne 4) {
    throw "Act I hotspot map wet-beat count mismatch: expected 4, got $($wetRows.Count)"
}

foreach ($expectedWetKnot in @("salt_market_church_sign_wet", "fish_hall_drain", "registry_lamp_smoked", "old_quay_rope_cleat")) {
    if ($expectedWetKnot -notin @($wetRows | ForEach-Object { $_.wet_ink_knot })) {
        throw "Act I hotspot map missing wet Ink knot: $expectedWetKnot"
    }
}

$sabineExit = Require-Row { $_.room_id -eq "harbormaster_office" -and $_.name -eq "ToSabine" } "Harbormaster to Sabine exit"
if ($sabineExit.target_room -ne "SabineOffice" -or $sabineExit.requires_flags -ne "FL_rite_name|FL_rite_debt|FL_rite_heartbeat") {
    throw "Sabine exit export does not preserve the three-Rite gate."
}

powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot "Export-ActIHotspotOverlay.ps1")

if (-not (Test-Path -LiteralPath $overlayPath)) {
    throw "Missing Act I hotspot overlay export: $overlayPath"
}

if (-not (Test-Path -LiteralPath $layoutAuditPath)) {
    throw "Missing Act I hotspot layout audit export: $layoutAuditPath"
}

$layoutAudit = Get-Content -LiteralPath $layoutAuditPath -Raw
foreach ($requiredAuditText in @("Act I Hotspot Layout Audit", "Bounds: pass", "Close-Pair Review")) {
    if ($layoutAudit -notmatch [regex]::Escape($requiredAuditText)) {
        throw "Act I hotspot layout audit missing required marker text: $requiredAuditText"
    }
}

$overlay = Get-Content -LiteralPath $overlayPath -Raw
foreach ($roomId in $expectedRoomCounts.Keys) {
    if ($overlay -notmatch "room-$([regex]::Escape($roomId))") {
        throw "Act I hotspot overlay missing room panel: $roomId"
    }
}
foreach ($requiredText in @("A Corpse in Good Standing - Act I Hotspot Overlay", "duel Registrar", "alternate=old_quay_bollards_all_seen", "wet=salt_market_church_sign_wet")) {
    if ($overlay -notmatch [regex]::Escape($requiredText)) {
        throw "Act I hotspot overlay missing required marker text: $requiredText"
    }
}

Write-Host "Act I hotspot map validation passed: rows=$($rows.Count), rooms=$($expectedRoomCounts.Count), wet=$($wetRows.Count), overlay=ok, layoutAudit=ok, closePairs=$($closePairs.Count)"
