$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$latestNotesPath = Join-Path $root "docs\playtest\results\act_i_human_playtest_latest.md"
$trackerPath = Join-Path $root "docs\playtest\act_i_review_fix_tracker.json"
$decisionCsvPath = Join-Path $root "docs\playtest\act_i_review_decisions_template.csv"
$dashboardPath = Join-Path $root "docs\checkpoints\step_5_review_dashboard.json"
$reportPath = Join-Path $root "docs\playtest\act_i_review_handoff_sync.md"

foreach ($path in @($latestNotesPath, $trackerPath, $decisionCsvPath, $dashboardPath)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing Act I review handoff sync input: $path"
    }
}

$latestNotes = Get-Content -LiteralPath $latestNotesPath -Raw
$tracker = Get-Content -LiteralPath $trackerPath -Raw | ConvertFrom-Json
$decisionRows = @(Import-Csv -LiteralPath $decisionCsvPath)
$dashboard = Get-Content -LiteralPath $dashboardPath -Raw | ConvertFrom-Json
$rooms = @($tracker.rooms)

if ([string]$dashboard.generated_from -ne "docs/art/act_i_paintover_start_gate.json") {
    throw "Step 5 dashboard freshness proof is missing its paintover start-gate source."
}
if ([string]::IsNullOrWhiteSpace([string]$dashboard.generated_at_utc) -or [string]::IsNullOrWhiteSpace([string]$dashboard.source_modified_utc)) {
    throw "Step 5 dashboard freshness proof is missing generated_at_utc or source_modified_utc."
}

if ($rooms.Count -ne 11) {
    throw "Review handoff sync expected 11 tracker rooms, got $($rooms.Count)."
}
if ($decisionRows.Count -ne 11) {
    throw "Review handoff sync expected 11 decision CSV rows, got $($decisionRows.Count)."
}

$csvById = @{}
foreach ($row in $decisionRows) {
    $roomId = [string]$row.room_id
    if ([string]::IsNullOrWhiteSpace($roomId)) {
        throw "Review handoff CSV contains an empty room_id."
    }
    if ($csvById.ContainsKey($roomId)) {
        throw "Review handoff CSV contains duplicate room_id: $roomId"
    }
    $csvById[$roomId] = $row
}

$missingFromCsv = @()
$missingFromNotes = @()
$decisionMismatches = @()
foreach ($room in $rooms) {
    $roomId = [string]$room.room_id
    if (-not $csvById.ContainsKey($roomId)) {
        $missingFromCsv += $roomId
        continue
    }
    $csvRow = $csvById[$roomId]
    if ([string]$csvRow.decision -ne [string]$room.reviewer_decision) {
        $decisionMismatches += "$roomId tracker=$($room.reviewer_decision) csv=$($csvRow.decision)"
    }
    foreach ($requiredText in @([string]$room.room_code, [string]$room.title)) {
        if ($latestNotes -notmatch [regex]::Escape($requiredText)) {
            $missingFromNotes += "$roomId missing $requiredText"
        }
    }
}

foreach ($csvRoomId in $csvById.Keys) {
    if (-not @($rooms | Where-Object { $_.room_id -eq $csvRoomId }).Count) {
        throw "Review handoff CSV contains unknown room_id: $csvRoomId"
    }
}

if ($missingFromCsv.Count -gt 0) {
    throw "Review handoff CSV is missing rooms: $($missingFromCsv -join ', ')"
}
if ($missingFromNotes.Count -gt 0) {
    throw "Latest human review notes do not mention every tracker room: $($missingFromNotes -join '; ')"
}
if ($decisionMismatches.Count -gt 0) {
    throw "Review handoff CSV decisions differ from tracker decisions: $($decisionMismatches -join '; ')"
}

foreach ($requiredText in @(
    "Proceed to paintovers: yes / no",
    "Keep / revise before art / stop and redesign:",
    "Registrar duel staging preserves accepted Litany format",
    "Hard-R Float staging stays steam/silhouette/privacy only"
)) {
    if ($latestNotes -notmatch [regex]::Escape($requiredText)) {
        throw "Latest human review notes missing required review prompt: $requiredText"
    }
}

$dashboardArtifacts = @($dashboard.artifacts | ForEach-Object { [string]$_ })
foreach ($requiredArtifact in @(
    "docs/playtest/results/act_i_human_playtest_latest.md",
    "docs/playtest/act_i_review_decisions_template.csv",
    "docs/playtest/act_i_review_fix_tracker.md",
    "docs/art/act_i_review_contact_sheet.html"
)) {
    if ($requiredArtifact -notin $dashboardArtifacts) {
        throw "Step 5 dashboard missing review handoff artifact: $requiredArtifact"
    }
}

$pendingCount = @($decisionRows | Where-Object { $_.decision -eq "pending_review" }).Count
$approvedCount = @($decisionRows | Where-Object { $_.decision -eq "approved" }).Count
$reviseCount = @($decisionRows | Where-Object { $_.decision -eq "revise_before_art" }).Count
$stopCount = @($decisionRows | Where-Object { $_.decision -eq "stop_and_redesign" }).Count

$lines = @(
    "# Act I Review Handoff Sync",
    "",
    'Generated by `tools/Validate-ActIReviewHandoffSync.ps1`.',
    "",
    "Purpose: prove the latest human review notes, decision CSV, review tracker, and Step 5 dashboard all point at the same Act I room set before importing approvals.",
    "",
    "Tracker rooms: $($rooms.Count)",
    "Decision CSV rows: $($decisionRows.Count)",
    "Pending review: $pendingCount",
    "Approved: $approvedCount",
    "Revise before art: $reviseCount",
    "Stop and redesign: $stopCount",
    "",
    "Rule locks:",
    "- Latest notes must include the accepted Litany/Registrar duel-format prompt.",
    "- Latest notes must include the Grey Float hard-R staging prompt.",
    "- Dashboard must list the stable latest notes, decision CSV, review tracker, and contact sheet artifacts.",
    "",
    "| Room | Decision | CSV synced | Notes mention room |",
    "|---|---|---|---|"
)

foreach ($room in $rooms) {
    $lines += "| $($room.room_code) $($room.title) | $($room.reviewer_decision) | yes | yes |"
}

Set-Content -LiteralPath $reportPath -Value $lines -Encoding UTF8

$report = Get-Content -LiteralPath $reportPath -Raw
foreach ($forbiddenText in @("System.Object[]", "@{", "Ã¯Â»Â¿", "`t", "	ools/")) {
    if ($report.Contains($forbiddenText)) {
        throw "Act I review handoff sync report contains malformed Markdown: $forbiddenText"
    }
}
if ($report -match "[\x00-\x08\x0B\x0C\x0E-\x1F]") {
    throw "Act I review handoff sync report contains illegal control characters."
}

Write-Host "Act I review handoff sync validation passed: rooms=$($rooms.Count), csvRows=$($decisionRows.Count), pending=$pendingCount, approved=$approvedCount, revise=$reviseCount, stop=$stopCount."
